// ui/b/aboutdialog.vue
<!-- This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0 -->

<docs>
  # B-ABOUTDIALOG
  A modal [b-dialog] that displays version information about Anklang.
  ## Events:
  *close*
  : A *close* event is emitted once the "Close" button activated.
</docs>

<style lang="scss">
  .b-aboutdialog c-grid {
    max-width: 100%;
    & > * { //* avoid visible overflow for worst-case resizing */
      overflow-wrap: break-word;
      min-width: 0; }
  }
  .b-aboutdialog .b-aboutdialog-header {
    grid-column: 1;
    text-align: right; vertical-align: top; font-weight: bold;
    padding-right: .5em; min-width: 15em; }
  .b-aboutdialog .b-aboutdialog-field {
    grid-column: 2;
    overflow-wrap: break-word;
    display: inline-block; white-space: pre-wrap; }
</style>

<template>
  <b-dialog class="b-aboutdialog" :shown="shown" @update:shown="$emit ('update:shown', $event)" >
    <template v-slot:header>
      <div>About ANKLANG</div>
    </template>
    <slot></slot>
    <c-grid>
      <template v-for="p in info_pairs" :key="'hf' + p[0]">
	<span class="b-aboutdialog-header" >{{ p[0] }}</span>
	<span class="b-aboutdialog-field"  >{{ p[1] }}</span>
      </template>
    </c-grid>
    <template v-slot:footer>
      <div><button autofocus @click="$emit ('update:shown', false)" > Close </button></div>
    </template>
  </b-dialog>
</template>

<script>
async function about_pairs() {
  const user_agent = navigator.userAgent.replace (/([)0-9]) ([A-Z])/gi, '$1\n$2');
  let array = [
    [ 'Anklang:',		CONFIG.version + ' (' + CONFIG.revdate.split (' ')[0] + ')' ],
    [ 'SoundEngine:',		await Ase.server.get_build_id() ],
    [ 'CLAP:',			await Ase.server.get_clap_version() ],
    [ 'FLAC:',		        await Ase.server.get_flac_version() ],
    [ 'Opus:',		        await Ase.server.get_opus_version() ],
    [ 'Vuejs:',			Vue.version ],
    [ 'User Agent:',		user_agent ],
  ];
  if (window.Electron)
    {
      const operating_system = window.Electron.platform + ' ' + window.Electron.arch + ' (' + window.Electron.os_release + ')';
      const parray = [
	[ 'Electron:',          window.Electron.versions.electron ],
	[ 'Chrome:',            window.Electron.versions.chrome ],
	[ 'Node.js:',           window.Electron.versions.node ],
	[ 'Libuv:',             window.Electron.versions.uv ],
	[ 'V8:',                window.Electron.versions.v8 ],
	[ 'OS:',		operating_system ],
      ];
      array = Array.prototype.concat (array, parray);
    }
  return array;
}

export default {
  sfc_template,
  props: {
    shown: { default: false, type: Boolean },
  },
  emits: { 'update:shown': null, },
  data() { return {
    info_pairs: [],
  }; },
  async created() {
    this.info_pairs = await about_pairs();
  },
};
</script>

// ui/b/aboutdialog.jsx
// This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0
// @ts-check

import { LitComponent, html, render, noChange, JsExtract, docs, ref } from '../little.js';
import * as Util from "../util.js";
import * as Dom from "../dom.js";

// == HTML ==
const HTML = (t, d) => html`
<dialog class="floating-dialog [&:not([open])]:hidden" ${ref (h => t.dialog = h)}>
  <div class="dialog-header">
    About ANKLANG
  </div>
  <div class="grid max-w-full">
    ${INFOS_HTML (t, d)}
  </div>
  <div class="dialog-footer">
    <button class="button-xl" autofocus @click=${e => t.emit_close()} > Close </button>
  </div>
</dialog>`;
const INFOS_HTML = (t, d) =>
  t.info_pairs.map (p => html`
    <span class="col-start-1 min-w-[15em] pr-2 text-right align-top font-bold"> ${p[0]} </span>
    <span class="col-start-2 whitespace-pre-wrap break-words"> ${p[1]} </span>
  `);

// == SCRIPT ==

/** @class BAboutDialog
 * @description
 * The <b-aboutdialog> element is a modal [dialog] that displays version information about Anklang.
 * ### Events:
 * *close*
 * : A *close* event is emitted once the "Close" button activated.
 */
export class BAboutDialog extends LitComponent {
  createRenderRoot() { return this; }
  render() { return HTML (this, {}); }
  static properties = {
    shown:	{ type: Boolean },
  };
  constructor()
  {
    super();
    this.shown = false;
    this.info_pairs = [];
    this.dialog = null;
    this.completed_promise = null;
  }
  updated (changed_props)
  {
    let info_promise;
    if (changed_props.has ('shown') && this.shown) {
      const load_infos = async () => {
	this.info_pairs = await about_pairs();
	this.requestUpdate(); // showModal with info_pairs
      };
      info_promise = load_infos();
    }
    if (this.shown && !this.dialog.open && this.info_pairs.length > 0) {
      Dom.show_modal (this.dialog, () => this.emit_close());
      const old_completed_promise = this.completed_promise;
      this.completed_promise = (async () => {
	await Promise.all ([old_completed_promise, info_promise, this.updateComplete]);
	this.completed_promise = null;
      }) ();
    }
    if (!this.shown && this.dialog.open) {
      this.close_dialog();
      this.requestUpdate();
    }
  }
  close_dialog (event = null)
  {
    Util.prevent_event (event);
    this.dialog.close();
    const old_completed_promise = this.completed_promise;
    this.completed_promise = (async () => {
      await Promise.all ([old_completed_promise, this.updateComplete]);
      this.completed_promise = null;
    }) ();
    return this.completed_promise;
  }
  emit_close (event = null)
  {
    Util.prevent_event (event);
    this.dispatchEvent (new CustomEvent ('close', { detail: {} }));
  }
  disconnectedCallback()
  {
    if (this.dialog.open) // ensure focus is restored
      this.dialog.close();
    super.disconnectedCallback();
  }
}
customElements.define ('b-aboutdialog', BAboutDialog);

async function about_pairs() {
  const user_agent = navigator.userAgent.replace (/([)0-9]) ([A-Z])/gi, '$1\n$2');
  let array = [
    [ 'Anklang:',		CONFIG.version + ' (' + CONFIG.revdate.split (' ')[0] + ')' ],
    [ 'SoundEngine:',		await Ase.server.get_build_id() ],
    [ 'FLAC:',		        await Ase.server.get_flac_version() ],
    [ 'Opus:',		        await Ase.server.get_opus_version() ],
    [ 'Sndfile:',	        await Ase.server.get_sndfile_version() ],
    [ 'Lit:',			CONFIG.lit_version ],
    [ 'User Agent:',		user_agent ],
  ];
  const Electron = window['Electron'];
  if (Electron)
    {
      const operating_system = Electron.platform + ' ' + Electron.arch + ' (' + Electron.os_release + ')';
      const parray = [
	[ 'Electron:',          Electron.versions.electron ],
	[ 'Chrome:',            Electron.versions.chrome ],
	[ 'Node.js:',           Electron.versions.node ],
	[ 'Libuv:',             Electron.versions.uv ],
	[ 'V8:',                Electron.versions.v8 ],
	[ 'OS:',		operating_system ],
      ];
      array = Array.prototype.concat (array, parray);
    }
  return array;
}
