// ui/b/buttonbar.tsx
// This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0
// @ts-check

import { LitComponent, html, JsExtract, docs } from '../little.js';

/** @class BButtonBar
 * @description
 * The <b-buttonbar> element is a container for tight packing of buttons.
 * ### Slots:
 * *slot*
 * : All contents passed into this element will be packed tightly and styled as buttons.
 */

// == STYLE ==
Extra_css`
b-buttonbar {
  display: inline-flex; background-color: var(--b-button-border);
  border: 1px solid var(--b-button-border);
  border-radius: var(--b-button-radius);
  > button, > .asbutton {
    margin: 0 0 0 1px;
    &:first-of-type	{ margin-left: 0; }
    &:first-of-type	{ border-top-left-radius: var(--b-button-radius); border-bottom-left-radius: var(--b-button-radius); }
    &:last-of-type	{ border-top-right-radius: var(--b-button-radius); border-bottom-right-radius: var(--b-button-radius); }
  }
}`;

// == HTML ==
const HTML = html`
  <slot></slot>
`;

// == SCRIPT ==
class BButtonBar extends LitComponent {
  createRenderRoot() { return this; }
  render = () => HTML;
}
customElements.define ('b-buttonbar', BButtonBar);

// ui/b/button-bar.vue
<!-- This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0 -->

<docs>
  # B-BUTTON-BAR
  A Vue container for tight packing of buttons.
  ## Slots:
  *slot*
  : All contents passed into this element will be packed tightly and styled as buttons.
</docs>

<style lang="scss">
  @import 'mixins.scss';
  .b-button-bar {
    display: inline-flex; background-color: $b-button-border;
    border: 1px solid $b-button-border;
    border-radius: var(--button-radius);
    > button, > push-button {
      margin: 0 0 0 1px;
      &:first-of-type	{ margin-left: 0; }
      &:first-of-type	{ border-top-left-radius: var(--button-radius); border-bottom-left-radius: var(--button-radius); }
      &:last-of-type	{ border-top-right-radius: var(--button-radius); border-bottom-right-radius: var(--button-radius); }
    }
  }
</style>

<template>
  <span class="b-button-bar" ><slot class="b-slot"></slot></span>
</template>

<script>
export default {
  sfc_template,
};
</script>
