// ui/b/cliplist.tsx
// This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0
// @ts-check

import { LitComponent, html, JsExtract, docs, ref } from '../little.js';
import * as Wrapper from '../wrapper.js';
import * as Util from '../util.js';
/** @typedef {import("../b/clipview.js").BClipView} BClipView */

/** ## Clip-List
 * The Clip-List allows to start playback of individual clips.
 */

// == STYLE ==
Extra_css`
b-cliplist {
  display: flex;
  position: relative;
  .-indicator {
    position: absolute; top: 0; bottom: 0; left: 0; width: 1px; height: 100%;
    background: var(--b-piano-roll-indicator);
    z-index: 2;
    transform: translateX(-9999px);
  }
  b-clipview {
    margin: 0 1px;
    width: var(--b-clipthumb-width);
    flex-shrink: 0; flex-grow: 0;
  }
}`;

// == HTML ==
const HTML = (t, d) => [
  t.wtrack.launcher_clips.map ((clip, index) =>
    html`  <b-clipview .clip=${clip} index=${index} .track=${t.track} trackindex=${t.trackindex} ></b-clipview>`
  ),
  html`    <span class="-indicator" ${ref (h => t.indicator_bar = h)}></span> `,
];

// == SCRIPT ==
const OBJECT_PROPERTY = { attribute: false };
const NUMBER_ATTRIBUTE = { type: Number, reflect: true }; // sync attribute with property

/// The <b-cliplist> element container holds BClipView elements.
export class BClipList extends LitComponent {
  createRenderRoot() { return this; }
  render()
  {
    const d = {};
    return HTML (this, d);
  }
  static properties = {
    track:	OBJECT_PROPERTY,
    trackindex:	NUMBER_ATTRIBUTE,
  };
  constructor()
  {
    super();
    this.track = null;
    this.wtrack = { launcher_clips: [] };	// dummy
    this.trackindex = -1;
    this.clipviews = [];
    this.teleobj = null;
    this.telemetry = null;
    this.ratiomul = window.devicePixelRatio;
    this.ratiodiv = 1.0 / this.ratiomul;
    /**@type{HTMLElement}*/
    this.indicator_bar = null;
    this.setAttribute ('data-f1', "cliplist.html");
  }
  connectedCallback() {
    super.connectedCallback();
    this.ratiomul = window.devicePixelRatio;
    this.ratiodiv = 1.0 / this.ratiomul;
  }
  disconnectedCallback() {
    super.disconnectedCallback();
    this.telemetry = null;
    Util.telemetry_unsubscribe (this.teleobj);
    this.teleobj = null;
  }
  updated (changed_props)
  {
    if (changed_props.has ('track'))
      {
	const weakthis = this.weak_this; // avoid strong wtrack->this refs for automatic cleanup
	console.assert (weakthis);
	this.wtrack = Wrapper.wrap_ase_object (this.track, { launcher_clips: [] }, () => weakthis.deref()?.requestUpdate());
	Util.telemetry_unsubscribe (this.teleobj);
	this.teleobj = null;
	const async_updates = async () => {
	  this.telemetry = await Object.freeze (this.track.telemetry());
	  if (!this.teleobj && this.telemetry)
	    ; // TODO: re-enable: this.teleobj = Util.telemetry_subscribe (this.recv_telemetry.bind (this), this.telemetry);
	};
	async_updates();
      }
    this.clipviews.length = 0;
    for (const element of this.querySelectorAll ("b-cliplist > b-clipview"))
      {
	const clipview = /**@type{BClipView}*/ (element);
	this.clipviews.push ({ width: clipview.getBoundingClientRect().width,
			       tickscale: clipview.tickscale,
			       x: clipview.offsetLeft, });
      }
  }
  recv_telemetry (teleobj, arrays)
  {
    const current = arrays[teleobj.current_clip.type][teleobj.current_clip.index];
    const tick = arrays[teleobj.current_tick.type][teleobj.current_tick.index];
    // const next = arrays[teleobj.next.type][teleobj.next.index];
    let u;
    if (current >= 0 && current < this.clipviews.length && tick >= 0)
      {
	const cv = this.clipviews[current];
	const t = cv.x + tick * cv.tickscale;
	u = Math.round (t * this.ratiomul) * this.ratiodiv; // screen pixel alignment
      }
    else
      u = -9999;
    if (u != this.last_pos)
      {
	this.indicator_bar.style.transform = "translateX(" + u + "px)";
	this.last_pos = u;
      }
    const [clip, tickfn] = Shell.piano_current();
    if (tickfn && clip == this.wtrack.launcher_clips[current])
      tickfn (this.wtrack.launcher_clips[current], tick);
  }
}
customElements.define ('b-cliplist', BClipList);

// ui/b/cliplist.vue
<!-- This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0 -->

<docs>
  # B-CLIPLIST
  A Vue template to display a list of Ase.Clip instances.
  ## Props:
  *project*
  : The project containing playback tracks.
  *track*
  : The Track containing the clips to display.
</docs>

<style lang="scss">
@import 'mixins.scss';
.b-cliplist {
  display: flex;
  position: relative;
  height: $b-trackrow-height;	//* fixed height is required to accurately calculate vertical scroll area */
  .-indicator {
    position: absolute; top: 0; bottom: 0; left: 0; width: 1px; height: 100%;
    background: $b-piano-roll-indicator;
    z-index: 2;
    transform: translateX(-9999px);
  }
  .b-clipview {
    margin: 0 1px;
    width: $b-clipthumb-width;
  }
}
</style>

<template>

  <div class="b-cliplist" >
    <b-clipview v-for="(clip, index) in clips" :key="clip.$id"
		:clip="clip" :index="index" :track="track" :trackindex="trackindex" />
    <span class="-indicator" ref="indicator" />
  </div>

</template>

<script>
import * as Ase from '../aseapi.js';

function cliplist_data () {
  const data = {
    clips:	{ default: [],		notify: n => this.track.on ("notify:clips", n),
		  getter: async c => Object.freeze (await this.track.list_clips()), },
    telemetry:	{ getter: async c => Object.freeze (this.track.telemetry()), },
  };
  return this.observable_from_getters (data, () => this.track);
}

export default {
  sfc_template,
  props: {
    track:	{ type: Ase.Track, },
    trackindex:	{ type: Number, },
  },
  data() { return cliplist_data.call (this); },
  methods: {
    dom_create () {
      this.ratiomul = window.devicePixelRatio;
      this.ratiodiv = 1.0 / this.ratiomul;
    },
    dom_update () {
      this.clipviews = [];
      for (const clipview of this.$el.querySelectorAll (".b-cliplist > .b-clipview")) {
	const cv = Util.vue_component (clipview);
	this.clipviews.push ({ width: clipview.getBoundingClientRect().width,
			       tickscale: cv.tickscale,
			       x: clipview.offsetLeft, });
      }
      if (!this.teleobj && this.telemetry)
	this.teleobj = Util.telemetry_subscribe (this.recv_telemetry.bind (this), this.telemetry);
    },
    dom_destroy () {
      Util.telemetry_unsubscribe (this.teleobj);
      this.teleobj = null;
    },
    recv_telemetry (teleobj, arrays) {
      const current = arrays[teleobj.current_clip.type][teleobj.current_clip.index];
      const tick = arrays[teleobj.current_tick.type][teleobj.current_tick.index];
      // const next = arrays[teleobj.next.type][teleobj.next.index];
      let u;
      if (current >= 0 && current < this.clipviews.length && tick >= 0)
	{
	  const cv = this.clipviews[current];
	  const t = cv.x + tick * cv.tickscale;
	  u = Math.round (t * this.ratiomul) * this.ratiodiv; // screen pixel alignment
	}
      else
	u = -9999;
      if (u != this.last_pos)
	{
	  this.$refs.indicator.style = "transform: translateX(" + u + "px);";
	  this.last_pos = u;
	}
      if (Shell.piano_current_clip == this.clips[current])
	Shell.piano_current_tick (this.clips[current], tick);
    },
  },
};

</script>
