// ui/b/contextmenu.tsx
// This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0

/** @class ContextMenu
 * @description
 * The ContextMenu component implements a modal popup that displays contextmenu choices,
 * based on `<button uri=... ic=... kbd=.../>` elements, see also [MenuRow](#MenuRow),
 * [MenuTitle](#MenuTitle) and [MenuSeparator](#MenuSeparator).
 * Menu actions are identified via URI attributes, they can be activated by calling a handler
 * which is assigned via the `.activate` property, or the actions can be checked for being disabled
 * by calling a handler which is assigned via the `.isactive` property.
 * The `ic` attribute on buttons embeds a `<b-icon ic=.../>` inside the buttons.
 * Using the `popup()` method, the menu can be shown via
 * [HTMLDialogElement.showModal](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/showModal).
 * Example:
 * ```tsx
 * <div onContextMenu={e => cm_ref.popup(e)}>
 *   <ContextMenu ref={cm_ref} activate={menuactivation}>
 *     <button ic="md-close" kbd="Shift+Ctrl+Q" uri="quit"> Quit </button>
 *   </ContextMenu>
 * </div>
 * ```
 * Note that keyboard presses, mouse clicks, drag selections and event bubbling can
 * all cause menu item clicks and contextmenu activation.
 * In order to deduplicate multiple events that arise from the same user interaction,
 * *one* popup request and *one* click activation is processed per animation frame.
 *
 * ### Props:
 * *activate (uri)*
 * : Callback handler which is called with a menu item URI once a menu item is activated.
 * : Note, this handler can be called with an URI for which `.isactive` previously returned `false`, in particular via hotkeys.
 * *isactive (uri)* -> Promise<bool>
 * : Async callback used to check for a particular menu item by URI to stay active or be disabled, called during popup().
 *
 * ### Attributes:
 * *xscale*
 * : Consider a wider area than the context menu width for popup positioning.
 * *yscale*
 * : Consider a taller area than the context menu height for popup positioning.
 *
 * ### Events:
 * *activate (event)*
 * : Event signaling activation of a menu item, the `uri` can be found via `get_uri (event.detail)`.
 * *close (event)*
 * : Event signaling closing of the menu, regardless of whether menu item activation occoured or not.
 *
 * ### Methods:
 * *popup (event, { origin, focus_uri, data-contextmenu })*
 * : Popup the contextmenu, propagation of `event` is halted and the event coordinates or target is
 * : used for positioning unless `origin` is given.
 * : The `origin` is a reference DOM element to use for drop-down positioning.
 * : The `focus_uri` is a `<button uri.../>` menu item URI to receive focus after popup.
 * : The `data-contextmenu` element (or `origin`) has the `data-contextmenu=true` attribute assigned during popup.
 * *close()*
 * : Hide the contextmenu.
 * *map_kbd_hotkeys (active)*
 * : Activate/deactivate a global hotkey map containing the `<button kbd=.../>` hotkeys specified in menu items.
 * : For hotkeys, no prior `.isactive` check is carried out.
 */

import { onMount, onCleanup } from 'solid-js';
import * as Util from "../util.js";
import * as Kbd from '../kbd.js';
import { text_content, get_uri, valid_uri, has_uri } from '../dom.js';
import * as Dom from "../dom.js";

// == STYLE ==
Extra_css`
@reference "../tailwind.css";
dialog.b-contextmenu {
  color: var(--b-menu-foreground);
  background-color: var(--b-menu-background);
  border: 1px outset oklch(from var(--b-menu-background) calc(l * 0.8) c h);
  box-shadow: var(--b-menu-box-shadow);
  padding: 0;
  /* showModal() sets position:fixed which breaks intrinsic sizing.
     Height is set explicitly in popup() based on content scrollHeight. */
  overflow-y: auto !important;
  overflow-x: hidden;
  &:not([open]) { display: none; }
}
dialog.b-contextmenu > .b-contextmenu-inner {
  @apply flex flex-col items-stretch justify-start p-2;
}
dialog.b-contextmenu::backdrop {
  /* Menu backdrop must be transparent, for one a popup menu is different from a modal dialog,
   * and second, showing a modal dialog via menu item would result in bad flickernig. */
  background: transparent;
}
.b-contextmenu :is(button, .asbutton, summary) {
  @apply hflex flex-nowrap items-stretch px-4 py-1 text-left;
  background: transparent; color: var(--b-menu-foreground); border: 1px solid transparent;
  cursor: pointer; user-select: none; outline: none; width: 100%;
  kbd { flex-grow: 1; color: oklch(from var(--b-menu-foreground) calc(l - 0.15) c h); }
  > b-icon:first-child {
    margin: 0 0.75rem 0 0;
    width: 2rem; height: 1rem;
    align-self: center;
  }
  kbd { font-family: inherit; text-align: right; margin-left: 2.5em; }
  kbd[data-can-remap] { font-style: italic; }
  &[turn] {
    flex-direction: column; align-items: center;
    > b-icon:first-child { margin: 0 0 var(--b-menu-spacing) 0; }
  }
  &[disabled], &[disabled] * {
    pointer-events: none;
    color: var(--b-menu-disabled);
    kbd { color: var(--b-menu-disabled-fill); }
  }
}
.b-contextmenu b-menurow button,
.b-contextmenu .b-menurow button {
  @apply px-1;
  min-width: 5rem; /* this aligns blocks of 2-digit numbers */
  > b-icon:first-child { @apply m-0 mb-1; }
}
.b-contextmenu button:focus {
  background-color: var(--b-menu-focus-bg); color: var(--b-menu-focus-fg); outline: none;
  kbd { color: inherit; }
  border: 1px solid oklch(from var(--b-menu-focus-bg) calc(l * 0.5) c h);
}
.b-contextmenu :is(button.active, button:focus.active, button:focus:active, button:active) {
  background-color: var(--b-menu-active-bg); color: var(--b-menu-active-fg); outline: none;
  kbd { color: inherit; }
  border: 1px solid oklch(from var(--b-menu-active-bg) calc(l * 0.5) c h);
}`;

// == SCRIPT ==
function menuitem_isdisabled (this: any)
{
  const uri = get_uri (this);
  const menudata = provide_menudata (this);
  if (valid_uri (uri)  && undefined !== menudata.checkeduris?.[uri])
    return !menudata.checkeduris[uri];
  if (Object.hasOwnProperty.call (this, 'disabled') &&
      (this.disabled === "" || !!this.disabled))
    return true;
  const disabled_attr = this instanceof Element ? this.getAttribute ('disabled') : null;
  if (disabled_attr != undefined && disabled_attr != null)
    return true;
  if (this.$attrs && (this.$attrs['disabled'] === "" || !!this.$attrs['disabled']))
    return true;
  return false;
}

export function provide_menudata (element)
{
  // find ContextMenu dialog
  const b_contextmenu = Util.closest (element, '.b-contextmenu');
  if (b_contextmenu && b_contextmenu.menudata)
    return b_contextmenu.menudata;
  // fallback
  return {
    close: () => undefined,
    isactive: uri => true,
    menu_stamp: 0,	// deduplicating frame_stamp() for contextmenu
    item_stamp: 0,	// deduplicating frame_stamp() for menuitem
    mapname: '',
    showicons: true,
  };
}

export function ContextMenu (props: {
  ref?: (el: HTMLDialogElement) => void;
  activate?: (uri: string, event?: Event) => void;
  isactive?: (uri: string) => (Promise<boolean> | boolean);
  showicons?: boolean;
  mapname?: string;
  class?: string;
  id?: string;
  xscale?: number;
  yscale?: number;
  onactivate?: (e: CustomEvent) => void;
  onclose?: (e: Event) => void;
  children?: any;
})
{
  let dialog_ref: HTMLDialogElement | undefined;
  let emit_close_ = 0;
  let page_x: number | undefined;
  let page_y: number | undefined;
  let origin_el: Element | null = null;
  let data_contextmenu: Element | null = null;
  let need_reposition = false;
  let keymap_: Util.KeymapEntry[] = [];
  let keymap_active = false;
  let observer_: MutationObserver | null = null;
  let allowed_click: Event | null = null;

  const menudata: any = {
    close: () => undefined,
    isactive: (uri: string) => valid_uri (uri) && (!props.isactive || props.isactive (uri)),
    menu_stamp: 0,
    item_stamp: 0,
    mapname: props.mapname || '',
    showicons: props.showicons !== false,
  };

  // === Methods ===

  // Keep a reference to the native close method before we overwrite it on the element
  const native_dialog_close = HTMLDialogElement.prototype.close;

  const close = () => {
    if (dialog_ref?.open) {
      native_dialog_close.call(dialog_ref);
    }
    toggle_force_children (true);
    origin_el = null;
    data_contextmenu?.removeAttribute ('data-contextmenu');
    data_contextmenu = null;
    (window as any).App?.zmove(); // force changes to be picked up
    if (emit_close_) {
      emit_close_--;
      const ev = new CustomEvent ('close', { detail: {} });
      props.onclose?.(ev);
      dialog_ref?.dispatchEvent (ev);
    }
  };

  const popup = (event?: Event, popup_options: any = {}) => {
    Util.prevent_event (event);
    if (dialog_ref?.open || Util.frame_stamp() == menudata.menu_stamp)
      return false; // duplicate popup request, only popup once per frame
    const origin = popup_options.origin === null ? null : (popup_options.origin || (event as any)?.currentTarget);
    if (origin instanceof Element && !Util.check_visibility (origin))
      return false; // cannot popup around hidden origin
    toggle_force_children (false); // add [disabled] attribute to children
    const toggles = toggle_active_children(); // concurrently, enable active children
    origin_el = origin instanceof Element ? origin : null;
    menudata.menu_stamp = Util.frame_stamp(); // allows one popup per frame
    if (event && (event as any).pageX && (event as any).pageY) {
      page_x = (event as any).pageX;
      page_y = (event as any).pageY;
    } else {
      page_x = page_y = undefined;
    }
    data_contextmenu = popup_options['data-contextmenu'] || origin_el;
    data_contextmenu?.setAttribute ('data-contextmenu', 'true');
    emit_close_++;
    // auto-focus a specific child, or the first child with uri
    const furi = popup_options.focus_uri ? 'uri="' + popup_options.focus_uri + '"' : 'uri';
    (async () => {
      if (!dialog_ref) return;
      Dom.show_modal (dialog_ref);
      // showModal() sets position:fixed which breaks intrinsic sizing on <dialog>.
      // Explicitly size the dialog to its content before repositioning.
      fit_and_reposition_dialog();
      need_reposition = true;
      dialog_ref.blur();
      (window as any).App?.zmove(); // force changes to be picked up
      // check items (and auto-focus)
      await toggles;
      fit_and_reposition_dialog();
      const qse = dialog_ref!.querySelector (`button[${furi}], .asbutton[${furi}]`) as HTMLElement | null;
      if (qse && !qse.getAttribute ('disabled'))
        qse.focus();
    })();
    return true;
  };

  const fit_and_reposition_dialog = () => {
    if (!dialog_ref) return;
    const inner = dialog_ref.querySelector ('.b-contextmenu-inner') as HTMLElement | null;
    if (inner) {
      const max_h = window.innerHeight - 40;
      dialog_ref.style.maxHeight = max_h + 'px';
      dialog_ref.style.height = Math.min (inner.scrollHeight, max_h) + 'px';
    }
    reposition_dialog();
  };

  const reposition_dialog = () => {
    if (!dialog_ref) return;
    const p = Util.popup_position (dialog_ref, {
      origin: origin_el, x: page_x, y: page_y,
      xscale: props.xscale ?? 1, yscale: props.yscale ?? 1,
    });
    dialog_ref.style.left = p.x + "px";
    dialog_ref.style.top = p.y + "px";
    dialog_ref.style.margin = "0";
  };

  const check_isactive = async (finduri: string | null = null) => {
    if (!dialog_ref) return null;
    const w = document.createTreeWalker (dialog_ref, NodeFilter.SHOW_ELEMENT);
    let hasuri: any = null, e: Node | null, a: Promise<any>[] = [];
    while ( (e = w.nextNode()) ) {
      const any_e: any = e;
      if (any_e.check_isactive) {
        if (get_uri (any_e) == finduri)
          hasuri = any_e;
        a.push (any_e.check_isactive());
      }
    }
    await Promise.all (a);
    return hasuri;
  };

  const find_menuitem = (uri: string) => {
    if (!dialog_ref) return null;
    const w = document.createTreeWalker (dialog_ref, NodeFilter.SHOW_ELEMENT);
    let e: Node | null;
    while ( (e = w.nextNode()) ) {
      if (get_uri (e as any) == uri)
        return e;
    }
    return null;
  };

  const map_kbd_hotkeys = (active = false) => {
    if (keymap_.length) {
      keymap_.length = 0;
      Util.remove_keymap (keymap_);
    }
    keymap_active = !!active;
    if (!keymap_active || !dialog_ref)
      return;
    const w = document.createTreeWalker (dialog_ref, NodeFilter.SHOW_ELEMENT);
    let e: Node | null;
    while ( (e = w.nextNode()) ) {
      const any_e: any = e;
      const keymap_entry = any_e['_keymap_entry'];
      if (keymap_entry instanceof Util.KeymapEntry)
        keymap_.push (keymap_entry);
    }
    if (keymap_.length)
      Util.add_keymap (keymap_);
  };

  const toggle_active_children = async () => {
    const this_isactive = props.isactive; // fetch function prop
    const isactive = async (uri: string) => !uri || !this_isactive || await this_isactive (uri);
    const proms: (Promise<boolean> & { element?: Element })[] = [];
    if (!dialog_ref) return;
    for (let b of dialog_ref.querySelectorAll ('button, .asbutton')) {
      const any_b = b as any;
      const uri = any_b.getAttribute ('uri');
      if (uri === null) continue;
      const promise = isactive (uri) as Promise<boolean> & { element?: Element };
      promise['element'] = b;
      proms.push (promise);
    }
    const toggles = await Promise.all (proms);
    stop_observer();
    for (let i = 0; i < proms.length; i++) {
      const element = proms[i]['element']!, disabled = !toggles[i];
      element.toggleAttribute ('disabled', disabled);
    }
    start_observer();
  };

  const toggle_force_children = (enabled: boolean) => {
    stop_observer();
    if (!dialog_ref) { start_observer(); return; }
    for (let b of dialog_ref.querySelectorAll ('button, .asbutton')) {
      const any_b = b as any;
      const uri = any_b.getAttribute ('uri');
      if (uri === null) continue;
      any_b.toggleAttribute ('disabled', !enabled);
    }
    start_observer();
  };

  const start_observer = () => {
    if (observer_ || !dialog_ref || !document.body.contains (dialog_ref)) return;
    observer_ = new MutationObserver (Util.debounce (() => {
      stop_observer();
      integrate_children();
      if (dialog_ref?.open)
        fit_and_reposition_dialog();
      start_observer();
    }));
    observer_.observe (dialog_ref, { childList: true, subtree: true, attributes: true });
  };

  const stop_observer = () => {
    if (!observer_) return;
    observer_.disconnect();
    observer_ = null;
  };

  /** Integrate button into contextmenu handling. */
  function integrate_button (this: HTMLElement, contextmenu: HTMLElement)
  {
    const btn = this;
    // focus on hover
    if (!btn.onmouseenter)
      btn.onmouseenter = () => btn.focus();
    // <b-icon ic/> - preserve existing or create one
    const ic_value = btn.getAttribute ('ic');
    if (ic_value) {
      const icon = btn.querySelector ('b-icon') || document.createElement ('b-icon');
      if (!icon.parentElement) {
        icon.className = "pointer-events-none";
        btn.prepend (icon);
      }
      icon.setAttribute ('ic', ic_value);
    } else
      btn.querySelector ('b-icon')?.remove();
    // aria-label
    const aria_label = text_content (btn, false).trim();
    btn.setAttribute ('aria-label', aria_label);
    // menurow children - turn/noturn based on parent .b-menurow
    const turn = !!Util.closest (btn, '.b-menurow:not(.noturn)');
    btn.toggleAttribute ("turn", turn);
    const noturn = !!Util.closest (btn, '.b-menurow.noturn');
    btn.toggleAttribute ("noturn", noturn);
    // <kbd/>
    const kbds = btn.getAttribute ('kbd');
    if (kbds) {
      const kbd = btn.querySelector ('kbd') || document.createElement ('kbd');
      if (!kbd.parentElement) {
        kbd.className = "pointer-events-none";
        btn.appendChild (kbd);
        kbd.innerText = kbds;
      }
      // hotkey
      if (!(btn as any)['_keymap_entry'])
        (btn as any)['_keymap_entry'] = new Util.KeymapEntry ('', btn.click.bind (btn), btn);
      const menudata = provide_menudata (btn);
      const shortcut = Kbd.shortcut_lookup (menudata.mapname, aria_label, kbds);
      if (shortcut != (btn as any)['_keymap_entry'].key)
        (btn as any)['_keymap_entry'].key = shortcut;
      kbd.innerText = Util.display_keyname (shortcut);
    } else
      btn.querySelector ('kbd')?.remove();
  }

  const integrate_children = () => {
    if (!dialog_ref) return;
    for (let b of dialog_ref.querySelectorAll ('button, .asbutton, summary')) {
      integrate_button.call (b as HTMLElement, dialog_ref);
    }
    // rebuild keymap
    map_kbd_hotkeys (keymap_active);
  };

  // === Event Handlers ===

  const handle_click = (event: MouseEvent) => {
    if (allowed_click === event)
      return;
    // Find the button that was clicked via event delegation
    const target = (event.target as Element).closest ('button, .asbutton, summary') as HTMLElement | null;
    if (!target) return;
    const uri = get_uri (target);
    if (!valid_uri (uri))
      return;
    Util.prevent_event (event);
    if (Util.frame_stamp() == menudata.menu_stamp)
      return;
    const isactive = !(target as any).check_isactive ? true : (target as any).check_isactive (false);
    if (isactive instanceof Promise) {
      (async () => (await isactive) && activate_item (event, uri)) ();
      return;
    }
    if (isactive)
      activate_item (event, uri);
  };

  const activate_item = (event: Event, uri: string) => {
    if (allowed_click)
      return;
    if (Util.frame_stamp() == menudata.menu_stamp)
      return;
    if (valid_uri (uri)) {
      menudata.menu_stamp = Util.frame_stamp();
      const proceed = true;
      if (proceed) {
        if (props.activate)
          props.activate (uri, event);
        else {
          const ev = new CustomEvent ('activate', { detail: { uri } });
          props.onactivate?.(ev);
          dialog_ref?.dispatchEvent (ev);
        }
      }
      close();
    } else
      console.error ("ContextMenu.activate_item: invalid uri:", uri);
  };

  const handle_keydown = (event: KeyboardEvent) => {
    if (event.keyCode === 27 && // Escape
        dialog_ref?.open && dialog_ref?.matches ('[open]:modal'))
      return; // bubble up to browser
    if (Util.keydown_move_focus (event))
      return; // handled, no-default
  };

  const handle_close = () => {
    // Called when dialog is closed natively (Escape, backdrop click)
    close();
  };

  // === Lifecycle ===

  onMount (() => {
    if (!dialog_ref) return;
    // Integrate button children (icons, kbd, etc.) after DOM is ready
    integrate_children();
    start_observer();
    // Ensure menudata is properly set up
    menudata.close = close;
    menudata.isactive = (uri: string) => valid_uri (uri) && (!props.isactive || props.isactive (uri));
    // Close on backdrop clicks (regression from Lit migration)
    Util.dialog_backdrop_autoclose (dialog_ref, true);
  });

  onCleanup (() => {
    if (dialog_ref)
      Util.dialog_backdrop_autoclose (dialog_ref, false);
    stop_observer();
    map_kbd_hotkeys (false);
  });

  const set_ref = (el: HTMLDialogElement) => {
    dialog_ref = el;
    // Attach methods to dialog element for imperative access
    // This must happen immediately (not in onMount) because parent effects may call them
    (el as any).popup = popup;
    (el as any).close = close;
    (el as any).map_kbd_hotkeys = map_kbd_hotkeys;
    (el as any).check_isactive = check_isactive;
    (el as any).find_menuitem = find_menuitem;
    // Store menudata for child lookups
    (el as any).menudata = menudata;
    props.ref?.(el);
  };

  return (
    <dialog
      ref={set_ref}
      class={"b-contextmenu" + (props.class ? " " + props.class : "")}
      id={props.id}
      onClick={handle_click}
      onKeyDown={handle_keydown}
      onClose={handle_close}
    >
      <div class="b-contextmenu-inner">
        {props.children}
      </div>
    </dialog>
  );
}

// ui/b/contextmenu.vue
<!-- This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0 -->

<docs>
  # B-CONTEXTMENU
  A modal popup that displays contextmenu choices, see [B-MENUITEM](#b-menuitem),
  [B-MENUSEPARATOR](#b-menuseparator).
  Using the `popup()` method, the menu can be popped up from the parent component,
  and setting up an `onclick` handler can be used to handle menuitem actions. Example:
  ```html
  <div @contextmenu.prevent="$refs.cmenu.popup">
    <b-contextmenu ref="cmenu" @click="menuactivation">...</b-contextmenu>
  </div>
  ```
  ## Props:
  *xscale*
  : Consider a wider area than the context menu width for popup positioning.
  *yscale*
  : Consider a taller area than the context menu height for popup positioning.
  ## Events:
  *click (uri)*
  : Event signaling activation of a submenu item, the `uri` of the submenu is provided as argument.
  *close*
  : Event signaling closing of a menu, regardless of whether menu item activation occoured or not.
  *startfocus*
  : Auto focus a menu item upon popup, in the same way menu bar menus work.
  *keepmounted*
  : Keep the menu and menu items mounted at all times, needed for map_kbd_hotkeys().
  ## Methods:
  *popup (event, { origin, data-contextmenu })*
  : Popup the contextmenu, the `event` coordinates are used for positioning, the `origin` is a
  : reference DOM element to use for drop-down positioning. The `data-contextmenu` element (or `origin`)
  : has the `data-contextmenu=true` attribute assigned during popup.
  *close()*
  : Hide the contextmenu.
  *map_kbd_hotkeys (active)*
  : Activate (deactivate) the `kbd=...` hotkeys specified in menu items.
</docs>

<style lang="scss">
  @import 'mixins.scss';
  body div.b-contextmenu-area {				    //* constraint area for context menu placement */
    position: fixed; right: 0; bottom: 0;		    //* fixed bottom right */
    display: flex; flex-direction: column; align-items: flex-start;
    //* transition */
    $timing: 0.1s;
    &.v-enter-active	{ transition: opacity $timing ease-out, transform $timing linear; }
    &.v-leave-active	{ transition: opacity $timing ease-in,  transform $timing linear; }
    &.v-enter	 	{ opacity: 0.3; transform: translateX(0%) translateY(0%); }
    &.v-leave-to	{ opacity: 0; transform: translateX(-0%) translateY(-0%) scale(1); }
    &.b-contextmenu-notransitions { transition: none !important; }
  }
  body .b-contextmenu-shield {
    background: #0001;
    transition: background 0.1s;
  }
  body .b-contextmenu-area .b-contextmenu {	//* since menus are often embedded, this needs high specificity */
    //* The template uses flex+start for layouting to scroll without vertical shrinking */
    position: relative; max-width: 100%; max-height: 100%;  //* constrain to .b-contextmenu-area */
    overflow-y: auto; overflow-x: hidden;		    //* scroll if necessary */
    padding: $b-menu-padding 0;
    background-color: $b-menu-background; border: 1px outset darken($b-menu-background, 20%);
    color: $b-menu-foreground;
    box-shadow: $b-menu-box-shadow;
    [disabled], [disabled] * { pointer-events: none; }
  }
</style>

<template>
  <transition>
    <div class='b-contextmenu-area' :class='cmenu_class' ref='contextmenuarea' v-show='visible' >
      <v-flex class='b-contextmenu' ref='cmenu' start v-if='visible || keepmounted' >
	<slot />
      </v-flex>
    </div>
  </transition>
</template>

<script>
import * as Util from '../util.js';

const menuitem_onclick = function (event) {
  this.$emit ('click', this.uri, event);
  if (!event.defaultPrevented)
    {
      if (this.uri !== undefined && this.menudata.clicked)
	this.menudata.clicked (this.uri);
      else if (this.menudata.close)
	this.menudata.close();
    }
  event.stopPropagation();
  event.preventDefault(); // avoid submit, etc
};

const menuitem_isdisabled = function () {
  if (this.uri && undefined !== this.menudata.checkeduris[this.uri])
    return !this.menudata.checkeduris[this.uri];
  if (this.disabled === "" || !!this.disabled ||
      (this.$attrs && (this.$attrs['disabled'] === "" || !!this.$attrs['disabled'])))
    return true;
  return false;
};

export default {
  sfc_template,
  emits: { click: uri => !!uri,
	   close: null, },
  props: { notransitions: { default: false },
	   keepmounted: { type: Boolean, },
	   startfocus: { type: Boolean, },
	   xscale: { default: 1, },
	   yscale: { default: 1, }, },
  computed: {
    cmenu_class() { return this.notransitions !== false ? 'b-contextmenu-notransitions' : ''; },
  },
  data() { return { visible: false, doc_x: undefined, doc_y: undefined,
		    resize_observer: undefined, checkeduris: {},
		    showicons: true, popup_options: {},
		    onclick: menuitem_onclick, isdisabled: menuitem_isdisabled, }; },
  provide: Util.fwdprovide ('b-contextmenu.menudata',	// context for menuitem descendants
			    [ 'checkeduris', 'showicons', 'keepmounted', 'clicked', 'close', 'onclick', 'isdisabled' ]),
  beforeUnmount() {
    this.map_kbd_hotkeys (false);
  },
  unmounted () {
    this.map_kbd_hotkeys (false);
  },
  methods: {
    dom_update () {
      if (!this.resize_observer)
	{
	  this.resize_observer = new Util.ResizeObserver ((e, ro) => {
	    if (this.resize_timer)
	      return;
	    this.resize_timer = setTimeout (() => {
	      this.resize_timer = 0;
	      this.position_popup();
	    }, 1);
	  });
	}
      else if (this.resize_timer)
	{
	  clearTimeout (this.resize_timer);
	  this.resize_timer = 0;
	}
      this.resize_observer.disconnect();
      this.update_shield();
      if (this.$refs.cmenu)
	{
	  this.checkitems();
	  this.position_popup();
	  this.resize_observer.observe (document.body);
	  if (this.popup_options?.origin)
	    this.resize_observer.observe (this.popup_options.origin.$el || this.popup_options.origin);
	}
      if (!this.$refs.cmenu || !this.visible)
	this.clear_data_contextmenu();
      if (this.visible && !this.was_visible && this.startfocus)
	Util.move_focus (-999999);
      else if (!this.visible && this.was_visible)
	Util.forget_focus (this.$el);
      this.was_visible = this.visible;
    },
    clear_data_contextmenu ()
    {
      if (this._data_contextmenu_element)
	{
	  this._data_contextmenu_element.removeAttribute ('data-contextmenu');
	  this._data_contextmenu_element = undefined;
	}
    },
    add_data_contextmenu (element)
    {
      this.clear_data_contextmenu();
      this._data_contextmenu_element = element;
      this._data_contextmenu_element.setAttribute ('data-contextmenu', 'true');
    },
    dom_destroy () {
      this.clear_dragging();
      this.clear_data_contextmenu();
      this.resize_observer.disconnect();
      this.resize_observer = undefined;
      if (this.resize_timer)
	clearTimeout (this.resize_timer);
      this.resize_timer = 0;
      if (this.shield)
	this.shield.destroy (false);
      this.shield = undefined;
    },
    position_popup() {
      const area_el = this.$refs.contextmenuarea;
      if (area_el && area_el.getBoundingClientRect) // ignore Vue placeholder (html comment)
	{
	  const origin = this.popup_options.origin?.$el || this.popup_options.origin;
	  if (origin && Util.inside_display_none (origin))
	    {
	      this.close();
	      return;
	    }
	  const menu_el = this.$refs.cmenu;
	  // unset size constraints before calculating desired size, otherwise resizing
	  // can take dozens of resize_observer/popup_position frame iterations
	  area_el.style.left = '0px';
	  area_el.style.top = '0px';
	  const p = Util.popup_position (menu_el, { x: this.doc_x, xscale: this.xscale,
						    y: this.doc_y, yscale: this.yscale,
						    origin });
	  area_el.style.left = p.x + "px";
	  area_el.style.top = p.y + "px";
	}
    },
    checkitems() {
      if (!this.popup_options.checker)
	return;
      const checkrecursive = component => {
	if (component instanceof Element &&
	    component.__vue__)
	  component = component.__vue__;
	if (component.$options && component.$options.propsData && component.$options.propsData.uri)
	  {
	    let async_check = async () => {
	      let result = this.popup_options.checker.call (null, component.$options.propsData.uri, component);
	      result = await result;
	      if ('boolean' !== typeof result)
		result = undefined;
	      if (result != this.checkeduris[component.$options.propsData.uri])
		{
		  this.$set (this.checkeduris, component.$options.propsData.uri, result); // Vue reactivity
		  component.$forceUpdate();
		}
	    };
	    async_check();
	  }
	if (component.$children)
	  for (const child of component.$children)
	    checkrecursive (child);
	else if (component.children)    // DOM element, possibly a function component
	  for (const child of component.children)
	    checkrecursive (child);
      };
      if (this.$refs.cmenu)
	checkrecursive (this.$refs.cmenu);
    },
    update_shield() {
      const contextmenu = this.$refs.cmenu;
      if (!contextmenu && this.shield)
	{
	  this.shield.destroy (false);
	  this.shield = undefined;
	}
      if (contextmenu && this.visible && !this.shield)
	this.shield = Util.modal_shield (contextmenu, { class: 'b-contextmenu-shield',
							root: this.$refs.contextmenuarea,
							close: this.close });
    },
    popup (event, options) {
      this.popup_options = Object.assign ({}, options || {});
      this.visible = false;
      this.clear_data_contextmenu();
      this.clear_dragging();
      if (event && event.pageX && event.pageY)
	{
	  this.doc_x = event.pageX;
	  this.doc_y = event.pageY;
	}
      else
	this.doc_x = this.doc_y = undefined;
      if (event.type == "mousedown")
	{
	  console.assert (!this.dragging);
	  this.dragging = {
	    button: event.button,
	    ignoreclick: true,
	    timer: setTimeout (() => { if (this.dragging) this.dragging.ignoreclick = false; }, 500),
	    handler: (e) => this.drag_event (e),
	    evpassive: { capture: true, passive: true },
	    evactive: { capture: false, passive: false }
	  };
	  window.addEventListener ('mouseup',   this.dragging.handler, this.dragging.evactive);
	  window.addEventListener ('mousedown', this.dragging.handler, this.dragging.evpassive);
	  window.addEventListener ('keydown',   this.dragging.handler, this.dragging.evpassive);
	}
      const data_contextmenu_element = this.popup_options['data-contextmenu'] || this.popup_options.origin;
      if (data_contextmenu_element)
	this.add_data_contextmenu (data_contextmenu_element);
      this.visible = true;
      App.zmove(); // force changes to be picked up
    },
    clear_dragging() {
      if (!this.dragging)
	return;
      if (this.dragging.ignoreclick)
	clearTimeout (this.dragging.timer);
      window.removeEventListener ('mouseup',   this.dragging.handler, this.dragging.evactive);
      window.removeEventListener ('mousedown', this.dragging.handler, this.dragging.evpassive);
      window.removeEventListener ('keydown',   this.dragging.handler, this.dragging.evpassive);
      this.dragging = undefined;
    },
    drag_event (event) {
      console.assert (this.dragging);
      let clickit = null;
      if (this.visible && !this.dragging.ignoreclick &&
	  event.type == 'mouseup' && event.button == this.dragging.button &&
	  this.$refs.cmenu.contains (document.activeElement) &&
	  document.activeElement.contains (event.target))
	{
	  clickit = document.activeElement;
	  event.stopPropagation(); // avoid other 'mouseup' handlers
	  event.preventDefault();  // avoid generating 'click' from 'mouseup'
	}
      // clean up `dragging` state
      this.clear_dragging();
      // activate due to valid drag-selection
      if (clickit)
	Util.keyboard_click (clickit);
    },
    close () {
      this.clear_dragging();
      if (!this.visible)
	return;
      this.visible = false;
      // take down shield immediately, to remove focus guards
      if (this.shield)
	this.shield.destroy (false);
      this.shield = undefined;
      this.$emit ('close');
      App.zmove(); // force changes to be picked up
    },
    clicked (uri) {
      this.$emit ('click', uri);
      this.close();
    },
    /// Activate or disable the `kbd=...` hotkeys in menu items.
    map_kbd_hotkeys (active = false) {
      if (Object.hasOwnProperty.call (this, 'active_kmap_'))
	{
	  for (const k in this.active_kmap_)
	    Util.remove_hotkey (k, this.active_kmap_[k]);
	  this.active_kmap_ = undefined;
	}
      if (!active || !this.$el)
	return;
      const kmap = {}; // key -> component
      const buildmap = v => {
	const key = Object.hasOwnProperty.call (v, 'kbd_hotkey') && v.kbd_hotkey();
	if (key)
	  kmap[key] = _ => v.$el && Util.keyboard_click (v.$el);
	for (const c of v.$children)
	  buildmap (c);
      };
      buildmap (this);
      this.active_kmap_ = kmap;
      for (const k in this.active_kmap_)
	Util.add_hotkey (k, this.active_kmap_[k], this.$el);
    },
    /// Find a menuitem via its `uri`.
    find_menuitem (uri) {
      const match_uri = e => {
	if (Object.hasOwnProperty.call (e, 'uri') && e.uri == uri)
	  return e;
	for (const c of e.$children)
	  {
	    const r = match_uri (c);
	    if (r)
	      return r;
	  }
	return undefined;
      };
      return match_uri (this);
    },
  },
};
</script>
