// ui/b/knob.vue
<!-- This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0 -->

<docs>
  # B-KNOB
  This element provides a knob for scalar inputs.
  It supports the Vue
  [v-model](https://vuejs.org/v2/guide/components-custom-events.html#Customizing-Component-v-model)
  protocol by emitting an `input` event on value changes and accepting inputs via the `value` prop.
  ## Props:
  *bidir*
  : Boolean, flag indicating bidirectional inputs with value range `-1…+1`.
  *value*
  : Float, the knob value to be displayed, the value range is `0…+1` if *bidir* is `false`.
  *format*
  : String, format specification for popup bubbles, containinig a number for the peak amplitude.
  *label*
  : String, text string for popup bubbles.
  *hscroll*
  : Boolean, adjust value with horizontal scrolling (without dragging).
  *vscroll*
  : Boolean, adjust value with vertical scrolling (without dragging).
  *width4height*
  : Automatically determine width from externally specified height (default), otherwise determines height.
  ## Events:
  *update:value (value)*
  : Value change notification event, the first argument is the new value.
  *reset:value ()*
  : Request to reset the value.
  ## Implementation Notes
  The knob is rendered based on an SVG drawing, which is arranged in such a
  way that adding rotational transforms to the SVG elements is sufficient to
  display varying knob levels.
  Chrome cannot render individual SVG nodes into seperate layers (GPU textures)
  so utilizing GPU acceleration requires splitting the original SVG into
  several SVG layers, each of which can be utilized as a seperate GPU texture with
  the CSS setting `will-change: transform`.
</docs>

<style lang="scss">
  @import 'mixins.scss';
  .b-knob {
    display: flex; position: relative;
    margin: 0; padding: 0; text-align: center;
    &.b-knob-h4w svg { position: absolute; width:  100%; } //* height for width */
    &.b-knob-w4h svg { position: absolute; height: 100%; } //* width for height */
    .b-knob-trf {
      will-change: transform; /* request GPU texture for fast transforms */
    }
    & svg.b-knob-sizer {
      //* empty SVG element, used by .b-knob to determine width from height from viewBox */
      position: relative; //* participate in layout space allocation */
    }
  }
</style>

<!-- NOTE: This implementation assumes the HTML embeds eknob.svg -->

<template>
  <div    class="b-knob" :class="width4height ? 'b-knob-w4h' : 'b-knob-h4w'" ref="bknob"
	  @pointerdown="drag_start" @dblclick.stop="dblclick"
	  :data-tip="data_tip()" :data-bubble="bubble_tip()" >
    <svg  class="b-knob-sizer" :viewBox="viewbox()" />
    <svg  class="b-knob-base"               :style="style()" :viewBox="viewbox()" >
      <use href="#eknob-base" />
    </svg>
    <svg  class="b-knob-h1light"            :style="style()" :viewBox="viewbox()" v-if="!bidi()">
      <use href="#eknob-h1light" />
    </svg>
    <svg  class="b-knob-needle  b-knob-trf" :style="style()" :viewBox="viewbox()">
      <use href="#eknob-needle" />
    </svg>
    <svg  class="b-knob-h1dark  b-knob-trf" :style="style()" :viewBox="viewbox()" v-if="!bidi()" >
      <use href="#eknob-h1dark" />
    </svg>
    <svg  class="b-knob-h2light b-knob-trf" :style="style()" :viewBox="viewbox()" v-if="!bidi()" >
      <use href="#eknob-h2light" />
    </svg>
    <svg  class="b-knob-h3light b-knob-trf" :style="style()" :viewBox="viewbox()" v-if="bidi()" >
      <use href="#eknob-h3light" />
    </svg>
    <svg  class="b-knob-h3dark  b-knob-trf" :style="style()" :viewBox="viewbox()" v-if="bidi()" >
      <use href="#eknob-h3dark" />
    </svg>
    <svg  class="b-knob-finish"             :style="style()" :viewBox="viewbox()">
      <use href="#eknob-finish" />
    </svg>
  </div>
</template>

<script>
// Fetch inlined knob SVG.
const eknob = document.querySelector ('#htmlbody-embedded-svgs svg#eknob');
console.assert (eknob, 'failed to find svg#eknob');
const eknob_origin = { x: 32, y: 32 };
/* Use pointer locks in Electron only, to avoid a big
 * "Your Pointer Is Grabbed!" warning popup by the browser.
 */
const USE_PTRLOCK = !!window.Electron;

export default {
  sfc_template,
  props: { bidir: { default: false },
	   value: { default: 0 },
	   format: { default: "100 %" },
	   label:   { type: String },
	   hscroll: { type: Boolean, default: true },
	   vscroll: { type: Boolean, default: true },
	   prop:    { default: null, },
	   width4height: { type: Boolean, default: true }, },
  emits: { 'update:value': null, 'reset:value': null, },
  data: () => ({
    scalar_: 0,
  }),
  watch: {
    label (vnew, vold) {
      if (this.$el?.data_bubble_active) Shell.data_bubble.update (this.$el);
    },
  },
  mounted() {
    this.$el.onwheel = this.wheel_event;
  },
  beforeUnmount () {
    this.unlock_pointer = this.unlock_pointer?. ();
    this.uncapture_wheel = this.uncapture_wheel?. ();
    if (this.pending_change)
      this.pending_change = cancelAnimationFrame (this.pending_change);
  },
  methods: {
    data_tip() {
      let tip = "**DRAG** Adjust Value **DBLCLICK** Reset Value";
      if (this.prop?.label_ && this.scalar_)
	{
	  let num = (this.scalar_ * this.value_).toFixed (this.digits_);
	  num = this.parts_[0] + num + this.parts_[1];
	  tip = '**' + this.prop?.label_ + '** ' + num + ' ' + tip;
	}
      return tip;
    },
    bubble_tip() {
      if (false && this.scalar_)
	{
	  let num = (this.scalar_ * this.value_).toFixed (this.digits_);
	  num = this.parts_[0] + num + this.parts_[1];
	  return num;
	}
      if (this.label)
	return this.label;
      let tip = '';
      if (this.prop?.label_ && this.prop?.nick_ && this.prop.label_ !== this.prop.nick_)
	tip = "**" + this.prop.nick_ + "** " + this.prop.label_ + " " + tip;
      else if (this.prop?.label_ || this.prop?.nick_)
	tip = "**" + (this.prop.label_ || this.prop.nick_) + "** · " + tip;
      return tip;
    },
    style (div = 0) {
      const sz = { w: eknob.viewBox.baseVal.width, h: eknob.viewBox.baseVal.height };
      const origin = eknob_origin.x / sz.w * 100 + '% ' + eknob_origin.y / sz.h * 100 + '%';
      return "transform-origin:" + origin;
    },
    viewbox() {
      return eknob.getAttribute ('viewBox');
    },
    bidi() {
      const unidir = !this.bidir || this.bidir == '0' || this.bidir == 'false';
      return !unidir;
    },
    dom_update() {
      if (!this.$el) // we need a second Vue.render() call for DOM alterations
	return this.$forceUpdate();
      if (this.bidi_ != this.bidi())
	{
	  this.bidi_ = this.bidi();
	  this.value_ = undefined;
	  this.point_ = 0; // internal drag position
	  const outer = this.$refs.bknob;
	  this.needle_ = outer.querySelector ('svg.b-knob-needle');
	  this.h1dark_  = this.bidi_ ? null : outer.querySelector ('svg.b-knob-h1dark');
	  this.h2light_ = this.bidi_ ? null : outer.querySelector ('svg.b-knob-h2light');
	  this.h3dark_  = this.bidi_ ? outer.querySelector ('svg.b-knob-h3dark') : null;
	  this.h3light_ = this.bidi_ ? outer.querySelector ('svg.b-knob-h3light') : null;
	}
      this.update_format();
      this.render_value (this.value);
    },
    emit_value (v) {
      this.$emit ('update:value', v);
    },
    granularity (ev) {
      let gran = 1 / 405;               // steps per full turn to feel natural
      if (ev.shiftKey)
        gran = gran * 0.1;              // slow down
      else if (ev.ctrlKey)
        gran = gran * 10;               // speed up
      if (ev.type == 'wheel')
        gran *= 1 / 3.75;                       // approximate mouse movements in pixels
      if (this.bidi_)
        gran = gran * 2;                // bi-directional knobs cover twice the value range
      return gran;
    },
    dblclick (ev) {
      this.drag_stop (ev);
      /* Avoid spurious dblclick restes that are delivered at the
       * falling edge of a drag operation. That is likely to
       * happen on touchpads with sometimes bouncing clicks.
       */
      if (this.allow_dblclick)
	this.$emit ('reset:value');
    },
    drag_start (ev) {
      // allow only primary button press
      if (ev.buttons != 1 || this.captureid_ !== undefined)
	{
	  this.drag_stop (ev);
	  return;
	}
      // setup drag mode
      try {
	this.$el.setPointerCapture (ev.pointerId);
	this.captureid_ = ev.pointerId;
      } catch (e) {
	// something went wrong, bail out the drag
	console.warn ('knob.vue:drag_start:', e.message);
	return this.drag_stop (ev);
      }
      this.$el.onpointermove = this.drag_move;
      this.$el.onpointerup = this.drag_stop;
      if (USE_PTRLOCK && this.captureid_ !== undefined)
	this.unlock_pointer = Util.request_pointer_lock (this.$el);
      this.uncapture_wheel = Util.capture_event ('wheel', this.wheel_event);
      // display data-bubble during drag and monitor movement distance
      Shell.data_bubble.force (this.$el);
      const DPR = Math.max (window.devicePixelRatio || 1, 1);
      this.last = { x: ev.pageX * DPR, y: ev.pageY * DPR };
      this.drag = USE_PTRLOCK ? { x: 0, y: 0 } : { x: ev.pageX * DPR, y: ev.pageY * DPR };
      ev.preventDefault();
      ev.stopPropagation();
      this.allow_dblclick = true;
    },
    drag_stop (ev) {
      // unset drag mode
      this.unlock_pointer = this.unlock_pointer?. ();
      this.uncapture_wheel = this.uncapture_wheel?. ();
      if (this.captureid_ !== undefined)
	this.$el.releasePointerCapture (this.captureid_);
      if (this.pending_change)
	this.pending_change = cancelAnimationFrame (this.pending_change);
      this.$el.onpointermove = null;
      this.$el.onpointerup = null;
      this.captureid_ = undefined;
      this.last = null;
      this.drag = null;
      Shell.data_bubble.unforce (this.$el);
      if (!ev)
	return;
      ev.preventDefault();
      ev.stopPropagation();
    },
    drag_move (ev) {
      // store physical pixel movements (DPR) so knob behaviour is unrelated to display resolution
      if (!this.pending_change) // debounce value updates
	this.pending_change = requestAnimationFrame (this.drag_change);
      const DPR = Math.max (window.devicePixelRatio || 1, 1);
      if (USE_PTRLOCK)
	{
	  const dprfix = CONFIG.dpr_movement ? 1 : DPR;
	  this.drag.x += ev.movementX * dprfix;
	  this.drag.y += ev.movementY * dprfix;
	}
      else
	this.drag = { x: ev.pageX * DPR, y: ev.pageY * DPR };
      this.ptraccel = this.granularity (ev);
    },
    drag_change () {
      this.pending_change = null;
      const dx = (USE_PTRLOCK ? this.drag.x : this.drag.x - this.last.x) * 0.5;
      const dy =  USE_PTRLOCK ? this.drag.y : this.drag.y - this.last.y;
      let s = 1;          // by default Increase, and:
      if (dy > 0)         // if DOWN
	s = dx >= dy;     //   Decrease unless mostly RIGHT
      else if (dx < 0)    // if LEFT
	s = dy <= dx;     //   Decrease unless mostly UP
      const dist = (s ? +1 : -1) * Math.sqrt (dx * dx + dy * dy) * this.ptraccel;
      this.point_ = Util.clamp (this.point_ + dist, 0, +1);
      if (USE_PTRLOCK)
	this.drag = { x: 0, y: 0 };
      else
	this.last = { x: this.drag.x, y: this.drag.y };
      this.emit_value (this.point_);
      this.allow_dblclick = false;
    },
    wheel_event (ev) {
      const p = Util.wheel_delta (ev);
      if (this.captureid_ === undefined && // not dragging
	  ((!this.hscroll && p.x != 0) ||
	   (!this.vscroll && p.y != 0)))
	return;	// only consume scroll events if enabled
      const delta = -p.y || p.x * 0.5;
      const min = 0;
      if ((delta > 0 && this.value_ < 1) || (delta < 0 && this.value_ > min))
	{
	  const wheel_accel = this.granularity (ev);
	  this.point_ = Util.clamp (this.point_ + delta * wheel_accel, min, +1);
	  this.emit_value (this.point_);
	}
      ev.preventDefault();
      ev.stopPropagation();
      this.allow_dblclick = false;
    },
    update_format() {
      if (this.format_ === this.format)
	return;
      this.format_ = this.format;
      const parts = this.format_?.split (/(-?\d+(?:\.\d+)?)/); // [ prefix, number, rest... ]
      if (parts?.length >= 3)
	{
	  const prefix = parts.shift();
	  const num = parts.shift();
	  this.parts_ = [ prefix, parts.join ('') ];        // [ prefix, postfix ]
	  this.scalar_ = 1 * num;                           // integer digits
	  this.digits_ = (num.split ('.')[1] || "").length; // fractional digits
	}
      else
	{
	  this.parts_ = [ "", "" ]; // [ prefix, postfix ]
	  this.scalar_ = 10;        // integer digits
	  this.digits_ = 1;         // fractional digits
	}
    },
    render_value (value) {
      if (this.value_ === value)
	return;
      this.value_ = value;
      this.point_ = this.value_;
      let v = 135 * 2 * value - 135;
      if (this.bidi_)
	{
	  this.needle_.style['transform'] = 'rotate(' + v + 'deg)';
	  if (value < 0.5)
	    {
	      this.h3dark_.style['transform'] = 'scaleX(+1)';
	      v = value * 2 * 130;
	      this.h3light_.style['transform'] = 'rotate(' + v + 'deg)';
	    }
	  else
	    {
	      this.h3dark_.style['transform'] = 'scaleX(-1)';
	      v = 130 - 2 * (value - 0.5) * 130;
	      this.h3light_.style['transform'] = 'scaleX(-1) rotate(' + v + 'deg)';
	    }
	}
      else // !bidi_
	{
	  this.needle_.style['transform'] = 'rotate(' + v + 'deg)';
	  if (value < 0.5)
	    {
	      this.h2light_.style['transform'] = 'scale(0)';
	      v = 135 * 2 * value;
	      this.h1dark_.style['transform'] = 'rotate(' + v + 'deg)';
	    }
	  else
	    {
	      this.h1dark_.style['transform'] = 'scale(0)';
	      v = 135 * 2 * (value - 0.5) - 135;
	      this.h2light_.style['transform'] = 'rotate(' + v + 'deg)';
	    }
	}
      // to reduce CPU load, update data-bubble on demand only
      if (this.$el.data_bubble_active)
	; // Shell.data_bubble.update (this.$el);
    },
  },
};

</script>

// ui/b/knob.tsx
// This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0
// @ts-check

/** @class BKnob
 * @description
 * The `Knob` component renders a `.b-knob` element providing a knob for scalar inputs.
 * It supports the Vue
 * [v-model](https://vuejs.org/v2/guide/components-custom-events.html#Customizing-Component-v-model)
 * protocol by emitting an `input` event on value changes and accepting inputs via the `value` prop.
 * ### Props:
 * *bidir*
 * : Boolean, flag indicating bidirectional inputs with value range `-1…+1`.
 * *value*
 * : Float, the knob value to be displayed, the value range is `0…+1` if *bidir* is `false`.
 * *format*
 * : String, format specification for popup bubbles, containinig a number for the peak amplitude.
 * *label*
 * : String, text string for popup bubbles.
 * *hscroll*
 * : Boolean, adjust value with horizontal scrolling (without dragging).
 * *vscroll*
 * : Boolean, adjust value with vertical scrolling (without dragging).
 * *width4height*
 * : Automatically determine width from externally specified height (default), otherwise determines height.
 * ### Implementation Notes
 * The knob is rendered based on an SVG drawing, which is arranged in such a
 * way that adding rotational transforms to the SVG elements is sufficient to
 * display varying knob levels.
 * Chrome cannot render individual SVG nodes into seperate layers (GPU textures)
 * so utilizing GPU acceleration requires splitting the original SVG into
 * several SVG layers, each of which can be utilized as a seperate GPU texture with
 * the CSS setting `will-change: transform`.
 */

import { createEffect, mergeProps, onCleanup } from 'solid-js';
import * as Util from "../util.js";
import * as Mouse from '../mouse.js';

// == STYLE ==
Extra_css`
.b-knob {
  display: flex; position: relative;
  margin: 0; padding: 0; text-align: center;
  &[aria-disabled="true"] { opacity: 0.5; cursor: not-allowed; pointer-events: none; }
  &.b-knob-h4w svg { position: absolute; width:  100%; } /* height for width */
  &.b-knob-w4h svg { position: absolute; height: 100%; } /* width for height */
  .b-knob-trf {
    will-change: transform; /* request GPU texture for fast transforms */
  }
  svg.b-knob-sizer {
    /* empty SVG element, used by .b-knob to determine width from height from viewBox */
    position: relative; /* participate in layout space allocation */
  }
  #sprite {
    display: inline-block;
    background-image: url("/gen/assets/cknob193u.png");
    &[bidir] { background-image: url("/gen/assets/cknob193b.png"); }
    background-repeat: no-repeat;
    --b-knob-size: min(var(--b-prop-width), var(--b-prop-height));
    background-size: calc(1.0 * var(--b-knob-size));
    will-change: background-position;
    width:  calc(1.0 * var(--b-knob-size));
    height: calc(1.0 * var(--b-knob-size));
  }
}`;

// == Symbols & Constants ==
const SPIN_DRAG = Symbol ('SpinDrag');
const USE_PTRLOCK = true;

// == Helpers ==
/// Calculate spin drag acceleration (slowdown) from event type and modifiers.
function spin_drag_granularity (event)
{
  if (event.type == 'wheel') {
    let gran = 0.025;                   // approximate wheel delta "step" to percent
    if (event.shiftKey)
      gran = 0.005;                     // slow down
    else if (event.ctrlKey)
      gran = 0.10;                      // speed up
    return gran;
  }
  // pixel drag
  const radius = 64;                    // assumed knob size
  const circum = 2 * radius * Math.PI;
  let gran = 1 / circum;                // steps per full turn to feel natural
  if (event.shiftKey)
    gran = gran * 0.1;                  // slow down
  else if (event.ctrlKey)
    gran = gran * 10;                   // speed up
  return gran;
}

/** Turn accumulated spin drag motions into actual value changes.
 * @this{any}
 */
function spin_drag_change (this: any)
{
  const spin_drag = this, element = spin_drag.element;
  const drag = spin_drag.drag, last = spin_drag.last;
  const has_ptrlock = Util.has_pointer_lock (element);
  const dx = (has_ptrlock ? drag.x : drag.x - last.x) * 0.5;
  const dy =  has_ptrlock ? drag.y : drag.y - last.y;
  let s = true;       // adjust via Increase and:
  if (dy > 0)         // if DOWN
    s = dx >= dy;     //   Decrease unless mostly RIGHT
  else if (dx < 0)    // if LEFT
    s = dy <= dx;     //   Decrease unless mostly UP
  // reset drag accumulator
  if (has_ptrlock)
    spin_drag.drag = { x: 0, y: 0 };
  else
    spin_drag.last = { x: drag.x, y: drag.y };
  // determine accumulated distance
  let dist = (s ? +1 : -1) * Math.sqrt (dx * dx + dy * dy) * spin_drag.ptraccel;
  // convert to physical pixel movements, so knob behaviour is unrelated to display resolution
  if (!has_ptrlock ||
      (has_ptrlock && CONFIG.dpr_movement))
    {
      const DPR = window.devicePixelRatio || 1;
      dist *= DPR;
    }
  // assign value, stop dragging if return is true
  if (spin_drag.value_callback (dist))
    spin_drag_stop (element);
}

/** Handle sping drag pointer motion.
 * @this{any}
 */
function spin_drag_pointermove (this: any, event)
{
  console.assert (event.type === 'pointermove');
  const spin_drag = this, element = spin_drag.element;
  if (!spin_drag.pending_change) // debounce value updates
    spin_drag.pending_change = requestAnimationFrame (() => {
      spin_drag.pending_change = null;
      spin_drag_change.call (spin_drag);
    });
  const has_ptrlock = Util.has_pointer_lock (element);
  if (has_ptrlock)
    {
      spin_drag.drag.x += event.movementX;
      spin_drag.drag.y += event.movementY;
    }
  else
    spin_drag.drag = { x: event.pageX, y: event.pageY };
  spin_drag.ptraccel = spin_drag_granularity (event);
  spin_drag.stop_event (event);
}

/** Stop sping drag event handlers and pointer grab.
 * @this{any}
 */
function spin_drag_stop (this: any, event_or_element = undefined)
{
  const spin_drag = event_or_element instanceof MouseEvent ? this : event_or_element[SPIN_DRAG];
  if (!spin_drag?.stop)
    return;
  const element = spin_drag.element;
  if (event_or_element instanceof MouseEvent)
    spin_drag.stop_event (event_or_element);
  element.removeEventListener ('pointerup', spin_drag.stop);
  element.removeEventListener ('pointermove', spin_drag.pointermove);
  document.body.removeEventListener ('wheel', spin_drag.stop_event, { capture: true, /*passive: false*/ });
  // unset drag mode
  spin_drag.unlock_pointer = spin_drag.unlock_pointer?.();
  if (spin_drag.captureid !== undefined)
    element.releasePointerCapture (spin_drag.captureid);
  spin_drag.captureid = undefined;
  spin_drag.pending_change = cancelAnimationFrame (spin_drag.pending_change);
  spin_drag.last = null;
  spin_drag.drag = null;
  spin_drag.pointermove = null;
  spin_drag.stop = null;
  delete element[SPIN_DRAG];
  Shell.data_bubble.unforce (element);
}

/// Setup drag handlers for numeric spin button behavior.
export function spin_drag_start (element, event, value_callback)
{
  console.assert (element instanceof Element);
  console.assert (event.type === 'pointerdown');
  // allow only primary button press (single click)
  if (event.buttons != 1 || element[SPIN_DRAG])
    {
      if (element[SPIN_DRAG])
	spin_drag_stop (element);
      return false;
    }
  const spin_drag: any = {};
  Object.assign (spin_drag, {
    element,
    value_callback,
    pending_change: null,
    captureid: undefined,
    unlock_pointer: undefined,
    stop_event: event => { event.preventDefault(); event.stopPropagation(); },
    pointermove: spin_drag_pointermove.bind (spin_drag),
    stop: spin_drag_stop.bind (spin_drag),
    ptraccel: 1.0,
    last: null,
    drag: null,
  });
  // setup drag mode
  try {
    spin_drag.element.setPointerCapture (event.pointerId);
    spin_drag.captureid = event.pointerId;
  } catch (e) {
    // something went wrong, bail out the drag
    console.warn ('drag_start: error:', (e as Error).message);
    return false;
  }
  // use pointer lock for knob turning
  if (USE_PTRLOCK)
    spin_drag.unlock_pointer = Util.request_pointer_lock (element);
  const has_ptrlock = Util.has_pointer_lock (element);
  spin_drag.last = { x: event.pageX, y: event.pageY };
  spin_drag.drag = has_ptrlock ? { x: 0, y: 0 } : { x: event.pageX, y: event.pageY };
  spin_drag.stop_event (event);
  document.body.addEventListener ('wheel', spin_drag.stop_event, { capture: true, passive: false });
  element.addEventListener ('pointermove', spin_drag.pointermove);
  element.addEventListener ('pointerup', spin_drag.stop);
  element[SPIN_DRAG] = spin_drag;
  Shell.data_bubble.force (element);
  return true; // spin drag started
}

// == COMPONENT ==
export function Knob (props: {
  prop?: any;
  nosize?: boolean;
  hscroll?: boolean;
  vscroll?: boolean;
  disabled?: boolean;
  [key: string]: any;
})
{
  // Restore Lit class defaults: horizontal wheel scrolls the panel, vertical wheel adjusts the knob.
  const props2 = mergeProps ({ hscroll: false, vscroll: true }, props);
  let root_el: HTMLDivElement | undefined;
  let sprite_el: HTMLDivElement | undefined;
  let clear_notify_cb: (() => void) | undefined;
  // Keep edits local during the grace period; notifications still refresh the backend value.
  let settle_timer = 0;
  let button1date = 0;
  let last_ = 0;
  let backend_value = 0;

  const relabel_cb = Util.debounce (relabel);
  const queue_commit = Util.debounce (commit_value);

  function reposition()
  {
    if (!sprite_el)
      return;
    const steps = 193 - 1;
    const r = Math.round (steps * last_);
    sprite_el.style.backgroundPosition = "0px calc(" + -r + " * var(--b-knob-size))";
    relabel_cb();
  }

  async function relabel()
  {
    let text = props.prop?.get_text();
    const label = props.prop?.label_;
    const nick = props.prop?.nick_;
    let tip = "**DRAG** Adjust Value **DBLCLICK** Reset Value";
    text = await text;
    if (nick)
      tip = '**' + nick + '** ' + text + ' ' + tip;
    let bubble = text;
    if (label)
      bubble = '' + label + '   ' + text;
    root_el?.setAttribute ('data-tip', tip);
    root_el?.setAttribute ('data-bubble', bubble);
    App.zmove();
  }

  function prop_changed (newprop: any)
  {
    clear_notify_cb?.();
    clear_notify_cb = undefined;
    clearTimeout (settle_timer);
    settle_timer = 0;
    if (!newprop)
      return;
    clear_notify_cb = newprop.on ('notify', () => notify_value());
    backend_value = newprop?.fetch_() ?? 0;
    last_ = backend_value;
    reposition();
    notify_value();
  }

  async function notify_value ()
  {
    backend_value = await props.prop?.get_normalized();
    if (!settle_timer) {
      last_ = backend_value;
      reposition();
    }
  }

  function show_edit ()
  {
    clearTimeout (settle_timer);
    settle_timer = window.setTimeout (() => {
      settle_timer = 0;
      last_ = backend_value;
      reposition();
    }, CONFIG.INPUT_EDIT_GRACE_MS);
    reposition();
    queue_commit();
  }

  function wheel_event (event: WheelEvent)
  {
    if (props.disabled)   // let scroll events pass through, no value changes
      return;
    const d = Mouse.wheel_delta (event);
    if ((sprite_el as any)?.[SPIN_DRAG]?.captureid === undefined && // not dragging
	((!props2.hscroll && d.x != 0) ||
	 (!props2.vscroll && d.y != 0))) // consume scroll iff hscroll/vscroll enabled
      return;	// only consume scroll events if enabled
    // handle one scroll direction at a time
    const delta = -d.y || d.x * 0.75;
    // base changes on last known knob state
    if ((delta > 0 && last_ < 1) || (delta < 0 && last_ > 0))
      {
	const wheel_accel = spin_drag_granularity (event);
	last_ = Util.clamp (last_ + delta * wheel_accel, 0, +1);
	show_edit();
      }
    event.preventDefault();
    event.stopPropagation();
  }

  function commit_value()
  {
    if (props.disabled)
      return;
    props.prop?.set_normalized (last_);
  }

  function pointerdown (event: PointerEvent)
  {
    if (props.disabled)   // no dragging or double-click reset when disabled
      return;
    // handle double click
    if (event.buttons == 1)
      {
        const now = Number (new Date());
        if (button1date && now - button1date <= 500)
          {
            button1date = 0;
            spin_drag_stop (sprite_el);
            props.prop?.reset();
            return;
          }
        else
          button1date = now;
      }
    spin_drag_start (sprite_el, event, drag_change);
  }

  function drag_change (distance: number)
  {
    last_ = Util.clamp (last_ + distance, 0, +1);
    show_edit();
  }

  // External prop changes trigger setup
  createEffect (() => {
    const p = props.prop;
    prop_changed (p);
  });

  // Cleanup on unmount: release notify subscription and abort any in-flight spin drag
  onCleanup (() => {
    spin_drag_stop (sprite_el);
    queue_commit.cancel();
    relabel_cb.cancel();
    clearTimeout (settle_timer);
    settle_timer = 0;
    clear_notify_cb?.();
    clear_notify_cb = undefined;
    sprite_el = undefined;
    root_el = undefined;
  });

  // Determine bidir from prop hints (reactive getter, tracks props.prop changes)
  const bidir = () => props.prop?.hints_?.search (/:bidir:/) >= 0;

  return (
    <div class="b-knob" aria-disabled={props.disabled || undefined} ref={root_el}>
      <div id="sprite" {...{ "bool:bidir": bidir() }} ref={sprite_el}
        onWheel={wheel_event}
        onPointerDown={pointerdown}
        onDblClick={Util.prevent_event}
      >
      </div>
    </div>
  );
}
