// ui/b/menubar.vue
<!-- This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0 -->

<docs>
  # B-MENUBAR
  The main menu bar at the top of the window.
</docs>

<style lang="scss">
  @import 'mixins.scss';
  .b-menubar {
    margin: 5px;
    .-stack {
      display: inline-block;
      position: relative;
      vertical-align: middle;
      width: 1em; height: 1em;
      & :not(:first-child) { position: absolute; top: 0; left: 0; }
    }
  }
</style>

<template>

  <h-flex class="b-menubar" style="justify-content: space-between" >
    <!-- main menu & controlbar -->

    <!-- menubar left -->
    <b-button-bar class="-menubar" >
      <!-- File Menu -->
      <push-button data-tip="**CLICK** File Menu" data-hotkey="Alt+F" @click="$refs.filemenu.popup ($event)" @mousedown="$refs.filemenu.popup ($event)" >
	<div class="-stack" >
	  <b-icon ic="bc-folder" />
	  <b-icon ic="bc-menumore" />
	</div>
	<b-contextmenu ref="filemenu" id="g-filemenu" :activate.prop="activate" :isactive.prop="isactive" startfocus1 >
	  <b-menuitem ic="fa-file-o"	kbd="Ctrl+N"		uri="loadnew" >	New Project		</b-menuitem>
	  <b-menuitem ic="fa-file-audio-o" kbd="Ctrl+O"		uri="load"    >	Open Project…		</b-menuitem>
	  <b-menuitem ic="mi-save_alt"     kbd="Ctrl+S"		uri="save"    >	Save Project		</b-menuitem>
	  <b-menuitem ic="fa-save"	   kbd="Shift+Ctrl+S"	uri="saveas"  >	Save As…		</b-menuitem>
	  <b-menuseparator style="margin: 7px"  />
	  <b-menuitem ic="fa-cog"          kbd="Ctrl+RawComma"	uri="prefs"   >	Preferences		</b-menuitem>
	  <b-menuseparator style="margin: 7px"  />
	  <b-menuitem ic="mi-close"        kbd="Shift+Ctrl+Q" uri="quit">	Quit			</b-menuitem>
	</b-contextmenu>
      </push-button>

      <!-- Edit Menu -->
      <push-button data-tip="**CLICK** Edit Menu" data-hotkey="Alt+E" @click="$refs.editmenu.popup ($event)" @mousedown="$refs.editmenu.popup ($event)" >
	<div class="-stack" >
	  <b-icon ic="mi-draw" />
	  <b-icon ic="bc-menumore" />
	</div>
	<b-contextmenu ref="editmenu" id="g-editmenu" :activate.prop="activate" :isactive.prop="isactive" startfocus >
	  <b-menuitem ic="mi-undo" :disabled="!true"
		      kbd="Ctrl+Z" uri="undo">	Undo	</b-menuitem>
	  <b-menuitem ic="mi-redo" :disabled="!true"
		      kbd="Shift+Ctrl+Z" uri="redo">	Redo	</b-menuitem>
	</b-contextmenu>
      </push-button>

      <!-- View Menu -->
      <push-button data-tip="**CLICK** View Menu" data-hotkey="Alt+V" @click="$refs.viewmenu.popup ($event)" @mousedown="$refs.viewmenu.popup ($event)" >
	<div class="-stack" >
	  <b-icon ic="fa-eye" />
	  <b-icon ic="bc-menumore" />
	</div>
	<b-contextmenu ref="viewmenu" id="g-viewmenu" :activate.prop="activate" :isactive.prop="isactive" startfocus >
	  <b-menuitem ic="mi-fullscreen" :disabled="!document.fullscreenEnabled"
		      kbd="F11" uri="fullscreen">	Toggle Fullscreen	</b-menuitem>
	  <b-menuitem ic="mi-zoom_in" v-if="window.Electron"
		      kbd="Ctrl++" uri="zoom-in">			Zoom In		</b-menuitem>
	  <b-menuitem ic="mi-zoom_out" v-if="window.Electron"
		      kbd="Ctrl+-" uri="zoom-out">			Zoom Out	</b-menuitem>
	  <b-menuitem ic="—" v-if="window.Electron"
		      kbd="Ctrl+0" uri="zoom-reset">			Reset Zoom	</b-menuitem>
	</b-contextmenu>
      </push-button>

    </b-button-bar>

    <!-- playcontrols -->
    <h-flex>
      <b-playcontrols :project="project"> </b-playcontrols>
      <b-positionview :project="project"> </b-positionview>
    </h-flex>

    <!-- menubar right -->
    <b-button-bar class="-menubar" >
      <!-- Help Menu -->
      <push-button data-tip="**CLICK** Help Menu" data-hotkey="Alt+H" @click="$refs.helpmenu.popup ($event)" @mousedown="$refs.helpmenu.popup ($event)" >
	<div class="-stack" >
	  <b-icon ic="fa-life-ring" />
	  <b-icon ic="bc-menumore" />
	</div>
	<b-contextmenu ref="helpmenu" id="g-helpmenu" :activate.prop="activate" :isactive.prop="isactive" startfocus >
	  <b-menuitem ic="mi-chrome_reader_mode"	uri="user-manual">	Anklang Manual…		</b-menuitem>
	  <b-menuitem ic="mi-chrome_reader_mode"	uri="dev-manual">	Development Reference…	</b-menuitem>
	  <b-menuseparator style="margin: 7px"  />
	  <b-menuitem ic="fa-id-card-o"		uri="about">	About…			</b-menuitem>
	</b-contextmenu>
      </push-button>
    </b-button-bar>

  </h-flex>

</template>

<script>
import * as Ase from '../aseapi.js';
import * as Util from "../util.js";

export default {
  sfc_template,
  props: {
    song: { type: Ase.Song, },
    project: { type: Ase.Project, },
  },
  data() {
    return { project_: null, project_cleanup1: null };
  },
  unmounted() {
    this.project_cleanup1?.();
    this.project_cleanup1 = null;
  },
  mounted() {
    this.$refs.filemenu.map_kbd_hotkeys (true);
    this.$refs.editmenu.map_kbd_hotkeys (true);
    this.$refs.viewmenu.map_kbd_hotkeys (true);
    this.$refs.helpmenu.map_kbd_hotkeys (true);
  },
  methods: {
    dom_update() {
      if (this.project != this.project_)
	{
	  this.project_cleanup1?.();
	  this.project_ = this.project;
	  this.project_cleanup1 = this.project_?.on ("notify:dirty", () => this.check_isactive());
	}
      this.check_isactive();
    },
    window_close() {
      window.close();
      // when we're running in the browser, window.close() might not work, so...
      setTimeout (() => {
	window.location.href = 'about:blank';
      }, 0);
    },
    check_isactive()
    {
      this.$refs.filemenu.check_isactive();
      this.$refs.editmenu.check_isactive();
      this.$refs.viewmenu.check_isactive();
      this.$refs.helpmenu.check_isactive();
    },
    async isactive (uri) {
      switch (uri) {
	case 'undo':
	  return this.project.can_undo();
	case 'redo':
	  return this.project.can_redo();
	default:
	  return true;
      }
    },
    async activate (uri, event) {
      let u, v;
      switch (uri) {
	case 'quit_discard':
	  window.close();
	  break;
	case 'quit':
	  v = App.async_button_dialog ("Save Project?",
				       "The current project may contain unsaved changes.\n" +
				       "Save changes to the project before closing?",
				       (window.Electron ?
					[ 'Discard Changes', { label: 'Cancel', autofocus: true }, 'Save' ] :
					[ 'Discard Changes', { label: 'Cancel', autofocus: true },
					  { label: 'Save', disabled: true } ]),
				       'QUESTION');
	  v = await v;
	  if (v == 0)
	    return this.window_close();
	  if (v == 2 && await save_project())
	    return this.window_close();
	  break;
	case 'about':
	  Data.show_about_dialog = !Data.show_about_dialog;
	  break;
	case 'user-manual':
	  u = location.origin + '/doc/anklang-manual.html';
	  window.open (u, '_blank');
	  break;
	case 'dev-manual':
	  u = location.origin + '/doc/anklang-internals.html';
	  window.open (u, '_blank');
	  break;
	case 'prefs':
	  Data.show_preferences_dialog = !Data.show_preferences_dialog;
	  break;
	case 'zoom-reset':
	  await window.Electron.call ('zoom_level', 0.0);
	  break;
	case 'zoom-in':
	  await window.Electron.call ('zoom_level', (await window.Electron.call ('zoom_level') + 1));
	  break;
	case 'zoom-out':
	  await window.Electron.call ('zoom_level', (await window.Electron.call ('zoom_level')) - 1);
	  break;
	case 'fullscreen':
	  if (document.fullscreen)
	    document.exitFullscreen();
	  else
	    document.body.requestFullscreen();
	  break;
	case 'undo':
	  await this.project.undo();
	  break;
	case 'redo':
	  await this.project.redo();
	  break;
	case 'loadnew':
	  App.load_project_checked();
	  break;
	case 'load':
	  open_file();
	  break;
	case 'save':
	  save_project();
	  break;
	case 'saveas':
	  save_project (true);
	  break;
      }
    },
  },
};

async function open_file() {
  const opt = {
    title:  Util.format_title ('Anklang', 'Select File To Open'),
    button: 'Open File',
    cwd:    open_file.last_dir || "MUSIC",
    filters: [ { name: 'Projects', extensions: ['anklang'] }, // TODO: filters
	       { name: 'Audio Files', extensions: [ 'anklang', 'mid', 'wav', 'mp3', 'ogg' ] },
	       { name: 'All Files', extensions: [ '*' ] }, ],
  };
  const filename = await App.shell.select_file (opt);
  if (!filename)
    return;
  open_file.last_dir = filename.replace (/[^\/]*$/, ''); // dirname
  const err = await App.load_project_checked (filename);
  if (err != Ase.Error.NONE)
    ; // load_project_checked() displays a dialog
}

async function save_project (asnew = false) {
  const opt = {
    title:  Util.format_title ('Anklang', 'Save Project'),
    button: 'Save As',
    cwd:    save_project.last_dir || "MUSIC",
    filters: [ { name: 'Projects', extensions: ['anklang'] }, ],
  };
  let filename = await Data.project.saved_filename();
  let replace = asnew ? 0 : !!filename;
  if (asnew || !filename)
    filename = await App.shell.select_file (opt);
  if (!filename)
    return false;
  save_project.last_dir = filename.replace (/[^\/]*$/, ''); // dirname
  //if (!filename.endsWith ('.anklang'))
  //  filename += '.anklang';
  if (0 && !replace) // TODO: if file_exists (filename)
    {
      replace = await App.async_button_dialog ("Replace Project?",
					       "Replace existing project file?\n" +
					       filename + ": File exists", [
						 'Cancel',
						 { label: 'Replace', autofocus: true }, ],
					       'QUESTION');
      if (replace != 1)
	return false;
    }
  const err = await App.save_project (filename);
  if (err === Ase.Error.NONE)
    {
      filename = await Data.project.saved_filename();
      let msg = '### Project Saved\n';
      msg += '  \n  \nProject saved to: ``' + filename + '``\n';
      Util.create_note (msg);
      return true;
    }
  await App.async_button_dialog ("File IO Error",
				 "Failed to save project.\n" +
				 filename + ": " +
				 await Ase.server.error_blurb (err), [
				   { label: 'Dismiss', autofocus: true }
				 ], 'ERROR');
  return false;
}

</script>

// ui/b/menubar.jsx
// This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0
// @ts-check

/** @class B-MenuBar
 * SolidJS component that displays the main menu bar with File, Edit, View, and Help menus.
 */

import { onMount } from 'solid-js';
import * as Util from "../util.js";
import * as Ase from '../../ase/gen/api-jsonipc.g.ts';
import { PositionView } from './positionview';
import { PlayControls } from './playcontrols';
import { basename, dirname, displayfs, displaybasename, displaydirname } from '../strings.js';
import { ButtonBar } from './buttonbar';
import { ContextMenu } from './contextmenu';
import { Icon } from './icon';

// == STYLE ==
Extra_css`
@reference "../tailwind.css";
.b-menubar {
  .asbutton {
    @apply button-down-within size-10;
    position: relative;
  }
}
.b-menubar-icon {
  position: absolute; inset: 0;
  display: inline-flex; justify-content: center;
  [ic] { inset: 0; position: absolute; vertical-align: middle; }

  &::after {
    content: ''; 		/* force rendering */
    position: absolute; width: 0; height: 0;
    right: 0px;			/* Position at the right */
    bottom: 0px;		/* Position at the bottom */
    border-left: 6px solid transparent;
    border-right: 6px solid transparent;
    border-top: 6px solid white; /* Create a downward-pointing arrow */
    border-bottom: 0;
    transform-origin: 100% 100%;
    transform: rotate(-45deg) translate(6px, -2px); /* Rotate to point into corner */
  }
}`;

// == Component ==
export function MenuBar (props)
{
  // refs for contextmenu elements
  /** @type {any} */ let filemenu;
  /** @type {any} */ let editmenu;
  /** @type {any} */ let viewmenu;
  /** @type {any} */ let helpmenu;
  // Hotkeys check isactive when pressed, so closed menus keep their items enabled.
  onMount (() => {
    for (const menu of [filemenu, editmenu, viewmenu, helpmenu])
      menu.map_kbd_hotkeys (true);
  });

  return (
    <div class={props.class ? 'hflex b-menubar m-2 ' + props.class : 'hflex b-menubar m-2'} style="justify-content: space-between">
      {/* menubar left */}
      <ButtonBar class="-menubar">
        {/* File Menu */}
        <div class="asbutton button-dim" data-tip="**CLICK** File Menu" data-hotkey="Alt+F"
             onClick={e => filemenu.popup (e)}
             onMouseDown={e => filemenu.popup (e)}
             id="g-filemenu">
          <div class="b-menubar-icon">
            <Icon ic="md-folder"/>
          </div>
          <ContextMenu ref={filemenu} activate={activate} isactive={isactive} items={[
            { uri: 'loadnew', label: 'New Project', icon: 'fa-file_o', kbd: 'Ctrl+N' },
            { uri: 'load', label: 'Open Project…', icon: 'fa-file_audio_o', kbd: 'Ctrl+O' },
            { uri: 'save', label: 'Save Project', icon: 'fa-save', kbd: 'Ctrl+S' },
            { uri: 'saveas', label: 'Save As…', icon: 'fa-save', kbd: 'Shift+Ctrl+S' },
            { type: 'separator' },
            { uri: 'prefs', label: 'Preferences', icon: 'fa-cog', kbd: 'Ctrl+RawComma' },
            { type: 'separator' },
            { uri: 'quit', label: 'Quit', icon: 'md-close', kbd: 'Shift+Ctrl+Q' },
          ]} />
        </div>

        {/* Edit Menu */}
        <div class="asbutton button-dim" data-tip="**CLICK** Edit Menu" data-hotkey="Alt+E"
             onClick={e => editmenu.popup (e)}
             onMouseDown={e => editmenu.popup (e)}
             id="g-editmenu">
          <div class="b-menubar-icon">
            <Icon ic="md-playlist_edit"/>
          </div>
          <ContextMenu ref={editmenu} activate={activate} isactive={isactive} items={[
            { uri: 'undo', label: 'Undo', icon: 'md-undo', kbd: 'Ctrl+Z' },
            { uri: 'redo', label: 'Redo', icon: 'md-redo', kbd: 'Shift+Ctrl+Z' },
          ]} />
        </div>

        {/* View Menu */}
        <div class="asbutton button-dim" data-tip="**CLICK** View Menu" data-hotkey="Alt+V"
             onClick={e => viewmenu.popup (e)}
             onMouseDown={e => viewmenu.popup (e)}
             id="g-viewmenu">
          <div class="b-menubar-icon">
            <Icon ic="fa-eye"/>
          </div>
          <ContextMenu ref={viewmenu} activate={activate} isactive={isactive} items={[
            { uri: 'fullscreen', label: 'Toggle Fullscreen', icon: 'md-fullscreen', kbd: 'F11', disabled: !document.fullscreenEnabled },
            ...electron_menuitems(),
          ]} />
        </div>
      </ButtonBar>

      {/* playcontrols */}
      <div class="hflex">
        <PlayControls />
        <PositionView />
      </div>

      {/* menubar right */}
      <ButtonBar class="-menubar">
        {/* Help Menu */}
        <div class="asbutton button-dim" data-tip="**CLICK** Help Menu" data-hotkey="Alt+H"
             onClick={e => helpmenu.popup (e)}
             onMouseDown={e => helpmenu.popup (e)}
             id="g-helpmenu">
          <div class="b-menubar-icon">
            <Icon ic="fa-life_ring"/>
          </div>
          <ContextMenu ref={helpmenu} activate={activate} isactive={isactive} items={[
            { uri: 'anklang-docu', label: 'Anklang Documentation…', icon: 'fa-book_open' },
            { type: 'separator' },
            { uri: 'about', label: 'About…', icon: 'oct-id_badge' },
          ]} />
        </div>
      </ButtonBar>
    </div>
  );
};

// == Electron-specific menu items ==
function electron_menuitems()
{
  return window['Electron'] ? [
    { uri: 'zoom-in', label: 'Zoom In', icon: 'cod-zoom_in', kbd: 'Ctrl++' },
    { uri: 'zoom-out', label: 'Zoom Out', icon: 'cod-zoom_out', kbd: 'Ctrl+-' },
    { uri: 'zoom-reset', label: 'Reset Zoom', icon: 'cod-screen_full', kbd: 'Ctrl+0' },
  ] : [];
};

// == Menu activation handlers ==
async function isactive (uri)
{
  switch (uri) {
    case 'undo':
      return Shell.project.can_undo();
    case 'redo':
      return Shell.project.can_redo();
    default:
      return true;
  }
}

async function activate (uri, event)
{
  const Electron = window["Electron"] || null;
  let u, v;
  switch (uri) {
    case 'quit_discard':
      window.close();
      break;
    case 'quit':
      v = App.async_button_dialog ("Save Project?",
                                   "The current project may contain unsaved changes.\n" +
                                   "Save changes to the project before closing?",
                                   (Electron ?
                                    [ 'Discard Changes', { label: 'Cancel', autofocus: true }, 'Save' ] :
                                    [ 'Discard Changes', { label: 'Cancel', autofocus: true },
                                      { label: 'Save', disabled: false } ]),
                                   'QUESTION');
      v = await v;
      if (v == 0)
        return window_close();
      if (v == 2 && await save_project())
        return window_close();
      break;
    case 'about':
      Shell.show_about_dialog (true);
      break;
    case 'anklang-docu':
      u = location.origin + '/anklang/index.html';
      window.open (u, '_blank');
      break;
    case 'prefs':
      Shell.r.show_preferences_dialog = !Shell.r.show_preferences_dialog;
      break;
    case 'zoom-reset':
      await Electron.call ('zoom_level', 0.0);
      break;
    case 'zoom-in':
      await Electron.call ('zoom_level', (await Electron.call ('zoom_level') + 1));
      break;
    case 'zoom-out':
      await Electron.call ('zoom_level', (await Electron.call ('zoom_level')) - 1);
      break;
    case 'fullscreen':
      if (document.fullscreen)
        document.exitFullscreen();
      else
        document.body.requestFullscreen();
      break;
    case 'undo':
      await Shell.project.undo();
      break;
    case 'redo':
      await Shell.project.redo();
      break;
    case 'loadnew':
      App.load_project_checked();
      break;
    case 'load':
      open_file();
      break;
    case 'save':
      save_project();
      break;
    case 'saveas':
      save_project (true);
      break;
  }
}

function window_close()
{
  window.close();
  // when we're running in the browser, window.close() might not work, so...
  setTimeout (() => {
    window.location.href = 'about:blank';
  }, 0);
}

async function open_file() {
  const opt = {
    title:  _('Open Project'),
    button: _('Open File'),
    cwd:    open_file_last_dir,
    filters: [ { name: 'Projects', extensions: ['anklang'] }, // TODO: filters
               { name: 'Audio Files', extensions: [ 'anklang', 'mid', 'wav', 'mp3', 'ogg' ] },
               { name: 'All Files', extensions: [ '*' ] }, ],
  };
  const filename = await Shell.select_file (opt);
  if (!filename)
    return;
  open_file_last_dir = dirname (filename);
  const err = await App.load_project_checked (filename);
  if (err != Ase.Error.NONE) {
    // load_project_checked() displays a dialog
  }
}
let open_file_last_dir = "~MUSIC";

async function save_project (asnew = false) {
  const opt = {
    title:  _('Save Project'),
    button: _('Save As'),
    cwd:    save_project_last_dir || "~MUSIC",
    existing: false,
    filters: [ { name: 'Projects', extensions: ['anklang'] }, ],
  };
  let filename = await Shell.project.saved_filename();
  let replace = asnew ? 0 : !!filename;
  if (asnew || !filename)
    filename = await Shell.select_file (opt);
  if (!filename)
    return false;
  save_project_last_dir = dirname (filename);
  if (0 && !replace) // TODO: if file_exists (filename)
    {
      replace = await App.async_button_dialog ("Replace Project?",
                                               "Replace existing project file?\n" +
                                               displayfs (filename) + ": File exists", [
                                                 'Cancel',
                                                 { label: 'Replace', autofocus: true }, ],
                                               'QUESTION');
      if (replace != 1)
        return false;
    }
  let msg, err = await App.save_project (filename);
  if (err === Ase.Error.NONE) {
    filename = await Shell.project.saved_filename(); // get canonicalized form
    msg = '### Project Saved\n  \n  \n';
    msg += 'Project successfully saved to:\n\n`' + displayfs (filename) + '`\n';
  } else {
    let errblurb = Ase.server.error_blurb (err);
    msg = '# File IO Error\n  \n  \n';
    msg += 'Failed to save project:\n\n';
    msg += '`' + displayfs (filename) + ": " + await errblurb + '`';
  }
  Shell.show_notice (msg);
  return err === Ase.Error.NONE;
}
let save_project_last_dir = "~MUSIC";
