// ui/b/partlist.tsx
// This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0

import { createEffect, createSignal, onCleanup, For } from 'solid-js';
import * as Util from '../util.js';
import { ClipView } from './clipview';

/** @class PartList
 * @description
 * The `PartList` component renders a `.b-partlist` element to arrange Clip objects for playback.
 */

// == STYLE ==
Extra_css`
.b-partlist {
  display: flex;
  position: relative;
  .b-clipview {
    margin: 0 1px;
    width: calc(5 * var(--b-clipthumb-width));
    flex-shrink: 0; flex-grow: 0;
  }
}`;

// == COMPONENT ==
export function PartList (props)
{
  const [parts, set_parts] = createSignal ([]);

  // Wrap track to react to arranger part changes
  createEffect (() => {
    const track = props.track;
    let wtrack = { arranger_parts: [] };	// dummy
    if (track && typeof track.arranger_parts === 'function')	// TODO: re-add Ase.Track.arranger_parts()
      wtrack = Util.wrap_ase_object (track, { arranger_parts: [] }, () => set_parts (wtrack.arranger_parts || []));
    set_parts (wtrack.arranger_parts || []);
    onCleanup (() => (wtrack as any)?.__cleanup__?.());
  });

  function dblclick (event)
  {
    if (props.track && typeof props.track.create_part === 'function')	// TODO: re-add Ase.Track.create_part()
      props.track.create_part (0);
  }

  return (
    <div class="b-partlist" data-f1="#part-list" onDblClick={dblclick}>
      <For each={parts ()}>
        {(clip, index) => (
          <ClipView clip={clip} index={index()} track={props.track} trackindex={props.trackindex} />
        )}
      </For>
    </div>
  );
}

// ui/b/partlist.vue
<!-- This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0 -->

<docs>
  # B-PARTLIST
  A Vue template to display a list of Ase.Part instances.
  ## Props:
  *project*
  : The project containing playback tracks.
  *track*
  : The Track containing the parts to display.
</docs>

<template>

  <div class="b-partlist" >
    <b-partthumb v-for="(tp, pindex) in parts" :key="tp.unique_id + '-' + tp.tick"
		 :part="tp.part" :tick="tp.tick" :trackindex="trackindex" :index="pindex" ></b-partthumb>
  </div>

</template>

<style lang="scss">
  @import 'mixins.scss';
  .b-partlist {
    display: inline-block;
    position: relative;
    height: $b-trackrow-height;	//* fixed height is required to accurately calculate vertical scroll area */
  }
</style>

<script>
import * as Util from '../util.js';
import * as Ase from '../aseapi.js';

export default {
  sfc_template,
  props: {
    'track': { type: Ase.Track, },
    'trackindex': { type: Number, },
  },
  watch: {
    track: { immediate: true, async handler (n, o) {
      let clips = await this.track.list_clips();
      clips = clips.map (async tpd => { tpd.unique_id = await tpd.clip.unique_id(); return tpd; });
      clips = await Promise.all (clips);
      this.parts = clips;
    } },
  },
  data() { return {
    parts: [],  // [{tick,clip,duration,unique_id}, ...]
  }; },
};

</script>
