// ui/b/preferencesdialog.jsx
// This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0
// @ts-check

/** @class B-PreferencesDialog
 * SolidJS component that displays a modal dialog to edit preferences.
 *
 * ### Props:
 * *shown*
 * : Boolean controlling dialog visibility.
 * *onClose*
 * : Callback invoked when the Close button is activated.
 */

import { createSignal, createEffect, onCleanup } from 'solid-js';
import * as Util from "../util.js";
import * as Ase from '../../ase/gen/api-jsonipc.g.ts';
import * as Dom from "../dom.js";
import { ObjectEditor } from './objecteditor.tsx';

// == STYLE ==
Extra_css`
dialog.b-preferencesdialog {
  margin: auto;
}
`;

// == Component ==
export function PreferencesDialog (props)
{
  let dialogRef;
  const [proplist, set_proplist] = createSignal ([]);
  let cancelled = false; // guard against showModal() after unmount
  let close_sent = false; // close at most once
  const close = () => {
    if (close_sent) return;
    close_sent = true;
    props.onClose?.();
  };

  // Watch shown prop to open/close dialog
  createEffect (() => {
    const shown = props.shown;
    if (shown && !dialogRef?.open) {
      document.startViewTransition (async () => {
        Dom.show_modal (dialogRef, close);
        await fetch_preferences ();
      });
    }
    if (!shown && dialogRef?.open) {
      dialogRef.close ();
    }
  });

  onCleanup (() => {
    cancelled = true;
    dialogRef?.close ();
    close ();
  });

  const handleClose = () => {
    close ();
  };

  const close_button_click = (event) => {
    if (event.shiftKey && event.ctrlKey && (event.altKey || event.metaKey)) {
      Util.prevent_event (event);
      fetch_preferences ();
      return;
    }
    if (!props.shown) return;
    Util.prevent_event (event);
    document.startViewTransition (() => {
      close ();
    });
  };

  async function fetch_preferences ()
  {
    const list = await access_preferences ();
    if (cancelled) return;
    set_proplist (list);
    debug ("fetch_preferences:", list);
  }

  return (
    <dialog
      class="b-preferencesdialog floating-dialog [&:not([open])]:hidden"
      ref={dialogRef}
      onClose={handleClose}
      exclusive={true}
      bwidth="9em"
      style="z-index: 93">
      <div class="dialog-header">Anklang Preferences</div>
      <ObjectEditor
        value={proplist ()}
        augment={augment_prop}
      />
      <div class="dialog-footer">
        <button class="button-xl" autofocus onClick={close_button_click}>Close</button>
      </div>
    </dialog>
  );
}

// == Helper functions (unchanged from Lit version) ==

async function access_preferences ()
{
  return Promise.all ((await Ase.server.list_preferences ()).sort ().map (id => Ase.server.access_preference (id)));
}

function augment_prop (xprop)
{
  if (xprop.has_choices_) {
    for (let i = 0; i < xprop.value_.choices.length; i++) {
      const c = xprop.value_.choices [i];
      if (xprop.ident_ == 'driver.pcm.devid')
        augment_choice_entry (c, 'pcm');
      else if (xprop.ident_.match (/midi/i))
        augment_choice_entry (c, 'midi');
    }
  }
}

function augment_choice_entry (c, devicetype)
{
  const is_midi = devicetype == 'midi';
  const is_usb = c.label.match (/^USB /) || c.blurb.match (/ at usb-/);
  if (is_usb)
    c.blurb = c.blurb.replace (/ at usb-[0-9].*/, ' (USB)');
  if (is_midi)
    c.blurb = c.blurb.replace (/\n/, ', ');
  const standard_icons = ['pcm', 'midi'];
  const icon_hints = c.icon.split (/\s*,\s*/);
  if (c.icon && icon_hints.length == 0 && !standard_icons.includes (c.icon.replace (/\W/, '')))
    return;
  const is_pcm = devicetype == 'pcm';
  if (c.ident.startsWith ("null"))
    c.icon = "md-not_interested"; // "fa-deaf";
  else if (c.ident.startsWith ("auto"))
    c.icon = "fa-cog";
  else if (is_midi) {
    if (c.label.match (/\bMIDI\W*$/))
      c.icon = 'fa-music';
    else if (is_usb)
      c.icon = 'uc-🎘';
    else
      c.icon = 'fa-music';
  } else if (is_pcm) {
    const is_rec  = c.blurb.match (/\d\*captur/i);
    const is_play = c.blurb.match (/\d\*play/i);
    if (c.ident.startsWith ("jack="))
      c.icon = "md-graphic_eq";
    else if (c.ident.startsWith ("alsa=pulse"))
      c.icon = "md-speaker_group";
    else if (c.label.startsWith ("HDMI"))
      c.icon = "fa-tv";
    else if (icon_hints.includes ("headset"))
      c.icon = "md-headset_mic";
    else if (icon_hints.includes ("recorder"))
      c.icon = "uc-🎙";
    else if (is_usb)
      c.icon = "fa-usb";
    else if (c.blurb.match (/\bModem\b/))
      c.icon = "uc-☎ ";
    else if (is_rec && !is_play)
      c.icon = "md-mic";
    else if (is_play && !is_rec)
      c.icon = "fa-volume_up";
    else
      c.icon = "uc-💻";
  } else
    c.icon = "md-not_interested";
}

// ui/b/preferencesdialog.vue
<!-- This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0 -->

<docs>
  # B-PREFERENCESDIALOG
  A modal [b-dialog] to edit preferences.
  ## Events:
  *close*
  : A *close* event is emitted once the "Close" button activated.
</docs>

<style lang="scss" >
  .b-preferencesdialog	{
    /* max-width: 70em; */
  }
</style>

<template>
  <b-dialog class="b-preferencesdialog" :shown="shown" @update:shown="$emit ('update:shown', $event)" >
    <template v-slot:header>
      <div>Anklang Preferences</div>
    </template>
    <b-objecteditor class="b-preferencesdialog-fed" ref="fedobject" :value="proplist" :augment="augment" >
    </b-objecteditor>
    <template v-slot:footer>
      <div><button autofocus @click="close_button_click" > Close </button></div>
    </template>
  </b-dialog>
</template>

<script>
import * as Util from "../util.js";

async function augment_property (xprop) {
  if (xprop.has_choices_)
    {
      // Object.assign (xprop, { title_: xprop.label_ + " Selection" });
      for (let i = 0; i < xprop.value_.choices.length; i++)
	{
	  const c = xprop.value_.choices[i];
	  if (xprop.ident_ == 'driver.pcm.devid')
	    augment_choice_entry (c, 'pcm');
	  else if (xprop.ident_.match (/midi/i))
	    augment_choice_entry (c, 'midi');
	}
    }
}

function augment_choice_entry (c, devicetype) {
  const is_midi = devicetype == 'midi';
  const is_usb = c.label.match (/^USB /) || c.blurb.match (/ at usb-/);
  if (is_usb)
    c.blurb = c.blurb.replace (/ at usb-[0-9].*/, ' (USB)');
  if (is_midi)
    c.blurb = c.blurb.replace (/\n/, ', ');
  const standard_icons = ['pcm', 'midi'];
  const icon_hints = c.icon.split (/\s*,\s*/);
  if (c.icon && icon_hints.length == 0 && !standard_icons.includes (c.icon.replace (/\W/, '')))
    return;
  const is_pcm = devicetype == 'pcm';
  if (c.ident.startsWith ("null"))
    c.icon = "mi-not_interested"; // "fa-deaf";
  else if (c.ident.startsWith ("auto"))
    c.icon = "fa-cog";
  else if (is_midi)
    {
      if (c.label.match (/\bMIDI\W*$/))
	c.icon = 'fa-music';
      else if (is_usb)
	c.icon = 'uc-🎘';
      else
	c.icon = 'fa-music';
    }
  else if (is_pcm)
    {
      const is_rec  = c.blurb.match (/\d\*captur/i);
      const is_play = c.blurb.match (/\d\*play/i);
      if (c.ident.startsWith ("jack="))
	c.icon = "mi-graphic_eq";
      else if (c.ident.startsWith ("alsa=pulse"))
	c.icon = "mi-speaker_group";
      else if (c.label.startsWith ("HDMI"))
	c.icon = "fa-tv";
      else if (icon_hints.includes ("headset"))
	c.icon = "mi-headset_mic";
      else if (icon_hints.includes ("recorder"))
	c.icon = "uc-🎙";
      else if (is_usb)
	c.icon = "fa-usb";
      else if (c.blurb.match (/\bModem\b/))
	c.icon = "uc-☎ ";
      else if (is_rec && !is_play)
	c.icon = "mi-mic";
      else if (is_play && !is_rec)
	c.icon = "fa-volume-up";
      else
	c.icon = "uc-💻";
    }
  else
    c.icon = "mi-not_interested";
}

async function access_preferences()
{
  if (this.all_prefs)
    return Promise.all ((await Ase.server.list_preferences()).sort().map (id => Ase.server.access_preference (id)));
  // Ase.server.access_prefs()
  const preferences = [ [ _("Synthesis Settings"),
			  "driver.pcm.devid", "driver.pcm.synth_latency" ],
			[ _("MIDI Settings"),
			  "driver.midi1.devid", "driver.midi2.devid", "driver.midi3.devid", "driver.midi4.devid" ],
  ];
  let props = []; // [ [group,promise]... ]
  for (const [group, ...idents] of preferences)
    for (const ident of idents)
      props.push ([ Ase.server.access_preference (ident), group ]); // [ [property_promise,group]... ]
  const result = [];
  for (let [property,group] of props) {
    property = Object.create (await property); // new Object with prototype
    property.group = () => group;
    result.push (property);
  }
  return result;
}

function component_data () {
  const data = {
    proplist: { default: [], getter: c => access_preferences.call (this),
		notify: n => { this.proprefresh = n; return () => this.proprefresh = null; }, },
  };
  return this.observable_from_getters (data, () => true);
}

export default {
  sfc_template,
  props: {
    shown: { default: false, type: Boolean },
  },
  emits: { 'update:shown': null, },
  data() { return component_data.call (this); },
  watch: {
    shown (vnew, vold) { if (vnew && this.prefrefresh) this.prefrefresh(); },
  },
  methods: {
    augment (p) { return augment_property.call (this, p); },
    close_button_click (event)
    {
      if (event.shiftKey && event.ctrlKey &&
	  (event.altKey || event.metaKey)) {
	Util.prevent_event (event);
	this.all_prefs = true;
	this.proprefresh();
      } else
	this.$emit ('update:shown', false);
    }
  },
};
</script>
