// ui/b/toggle.tsx
// This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0
// @ts-check

/** @class BToggle
 * @description
 * The <b-toggle> element implements a simple toggle button for boolean audio processor
 * input properties. Its `value` can be accessed as a property and `valuechange` is emitted
 * on changes.
 * ### Props:
 * *value*
 * : Boolean, the toggle value to be displayed, the values are `true` or `false`.
 * *label*
 * : String, label to be displayed inside the toggle button.
 * ### Events:
 * *valuechange*
 * : Event emitted whenever the value changes, which is provided as `event.target.value`.
 */

import { LitComponent, html, ref, JsExtract, docs } from '../little.js';
import * as Util from "../util.js";
import * as Kbd from '../kbd.js';
import * as ContextMenu from './contextmenu.js';

// == STYLE ==
Extra_css`
b-toggle {
  display: flex; position: relative;
  margin: 0; padding: 0; text-align: center;
  user-select: none;
  &[aria-disabled="true"] { opacity: 0.5; cursor: not-allowed; pointer-events: none; }
  .b-toggle-label {
    white-space: nowrap; overflow: hidden;
    height: 1.33em;
    &.b-toggle-empty { width: 2.2em; }
    align-self: center;
    border-radius: 3px;
    background-color: var(--b-toggle-0-bg);
    box-shadow: 0 0 3px #00000077;
  }
  .b-toggle-off {
    background: linear-gradient(177deg, var(--b-toggle-0-bh), var(--b-toggle-0-bl) 20%, var(--b-toggle-0-bd));
    &.b-toggle-press:hover  	{ filter: brightness(90%); }
  }
  .b-toggle-on {
    background: var(--b-toggle-1-bg);
    background: linear-gradient(177deg, var(--b-toggle-1-bh), var(--b-toggle-1-bl) 20%, var(--b-toggle-1-bd));
    &.b-toggle-press:hover	{ filter: brightness(95%); }
  }
}`;

// == HTML ==
const HTML = (t, d) => html`
<div ${ref (h => t.button_ = h)} class="b-toggle-label ${!t.label ? 'b-toggle-empty' : ''}"
     @pointerdown=${t.pointerdown} @pointerup=${t.pointerup} @dblclick=${t.dblclick} >
  ${t.label}
</div>
`;

// == SCRIPT ==
const BOOL_ATTRIBUTE = { type: Boolean, reflect: true }; // sync attribute with property
const STRING_ATTRIBUTE = { type: String, reflect: true }; // sync attribute with property
const PRIVATE_PROPERTY = { state: true };

class BToggle extends LitComponent {
  createRenderRoot() { return this; }
  render() { return HTML (this, {}); }
  static properties = {
    value: BOOL_ATTRIBUTE,
    label: STRING_ATTRIBUTE,
    buttondown_: PRIVATE_PROPERTY,
  };
  constructor()
  {
    super();
    this.value = false;
    this.buttondown_ = -1;
    this.label = 'Toggle';
    this.button_ = null;
  }
  connectedCallback() {
    super.connectedCallback();
    this.setAttribute ('data-tip', "**CLICK** Toggle Value");
  }
  updated (changed_props)
  {
    if (changed_props.has ('value')) {
      this.button_.classList.remove (this.value ? 'b-toggle-off' : 'b-toggle-on');
      this.button_.classList.add (this.value ? 'b-toggle-on' : 'b-toggle-off');
    }
  }
  dblclick (event)
  {
    // prevent double-clicks from propagating, since we always
    // handled it as single click already
    event.preventDefault();
    event.stopPropagation();
  }
  pointerdown (event)
  {
    // trigger only on primary button press
    if (this.buttondown_ < 0 && event.buttons == 1)
      {
	this.buttondown_ = event.buttons;
	this.button_.classList.add ('b-toggle-press');
	event.preventDefault();
	event.stopPropagation();
      }
  }
  pointerup (event)
  {
    if (this.buttondown_ >= 0)
      {
	this.buttondown_ = -1;
	this.button_.classList.remove ('b-toggle-press');
	event.preventDefault();
	event.stopPropagation();
	if (this.button_.matches (':hover')) {
	  this.value = !this.value;
	  this.dispatchEvent (new Event ('valuechange', { composed: true }));
	}
      }
  }
}
customElements.define ('b-toggle', BToggle);

// ui/b/toggle.vue
<!-- This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0 -->

<docs>
  # B-TOGGLE
  This element provides a toggle button for boolean inputs.
  It supports the Vue
  [v-model](https://vuejs.org/v2/guide/components-custom-events.html#Customizing-Component-v-model)
  protocol by emitting an `input` event on value changes and accepting inputs via the `value` prop.
  ## Props:
  *value*
  : Boolean, the toggle value to be displayed, the values are `true` or `false`.
  *label*
  : String, label to be displayed inside the toggle button.
  ## Events:
  *update:value (value)*
  : Value change notification event, the first argument is the new value.
</docs>

<style lang="scss">
  .b-toggle {
    display: flex; position: relative;
    margin: 0; padding: 0; text-align: center;
    user-select: none;
  }
  .b-toggle-label {
    //* flex-grow: 1; */
    white-space: nowrap; overflow: hidden;
    height: 1.33em;
    &.b-toggle-empty { width: 2.2em; }
    align-self: center;
    border-radius: 3px;
    background-color: $b-toggle-0-bg;
    box-shadow: 0 0 3px #00000077;

    .b-toggle-off & {
      background: linear-gradient(177deg, $b-toggle-0-bh, $b-toggle-0-bl 20%, $b-toggle-0-bd);
      &.b-toggle-press:hover  	{ filter: brightness(90%); }
    }
    .b-toggle-on & {
      background-color: $b-toggle-1-bg;
      background: linear-gradient(177deg, $b-toggle-1-bh, $b-toggle-1-bl 20%, $b-toggle-1-bd);
      &.b-toggle-press:hover	{ filter: brightness(95%); }
    }
  }
</style>

<template>
  <div    class="b-toggle" ref="btoggle" :style="style (1)"
	  data-tip="**CLICK** Toggle Value" >
    <div  ref="button" class="b-toggle-label" :class="!label ? 'b-toggle-empty' : ''"
	  @pointerdown="pointerdown" @dblclick="dblclick" >
      {{ label }}
    </div>
  </div>
</template>

<script>
export default {
  sfc_template,
  props: { value: { default: false },
	   label: { default: "Toggle" }, },
  emits: { 'update:value': null, },
  data: () => ({
    value_: 0,
    buttondown_: false,
  }),
  beforeUnmount () {
    window.removeEventListener ('pointerup', this.pointerup);
  },
  methods: {
    style (div = 0) {
      return ""; // FIXME
    },
    dom_update() {
      if (!this.$el) // we need a second Vue.render() call for DOM alterations
	return this.$forceUpdate();
      this.value_ = this.value;
      if (this.value_)
	{
	  this.$el.classList.add ('b-toggle-on');
	  this.$el.classList.remove ('b-toggle-off');
	}
      else
	{
	  this.$el.classList.remove ('b-toggle-on');
	  this.$el.classList.add ('b-toggle-off');
	}
    },
    emit_value (v) {
      this.$emit ('update:value', v);
    },
    dblclick (ev) {
      // prevent double-clicks from propagating, since we always
      // handled it as single click already
      ev.preventDefault();
      ev.stopPropagation();
    },
    pointerdown (ev) {
      // trigger only on primary button press
      if (!this.buttondown_ && ev.buttons == 1)
	{
	  this.buttondown_ = true;
	  this.$refs.button.classList.add ('b-toggle-press');
	  window.addEventListener ('pointerup', this.pointerup);
	  ev.preventDefault();
	  ev.stopPropagation();
	}
    },
    pointerup (ev) {
      window.removeEventListener ('pointerup', this.pointerup);
      this.$refs.button.classList.remove ('b-toggle-press');
      if (this.buttondown_)
	{
	  this.buttondown_ = false;
	  ev.preventDefault();
	  ev.stopPropagation();
	  if (this.$refs.button.matches (':hover'))
	    this.emit_value (!this.value_);
	}
    },
  },
};

</script>
